import { useEffect, useState } from 'react'
import { CheckCircle2, Clock3, Users } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Props = { userId: string; stats?: { subscribers?: number; watch_time_seconds?: number; watch_time_hours?: number } | null }
type Thresholds = { subscribers: number; watch_hours: number }
export default function MonetizationDashboard({ userId, stats }: Props) {
  const [thresholds, setThresholds] = useState<Thresholds>({ subscribers: 200, watch_hours: 500 }); const [status, setStatus] = useState('not_eligible'); const [application, setApplication] = useState<string | null>(null); const [message, setMessage] = useState('')
  const subscribers = Number(stats?.subscribers || 0); const hours = Number(stats?.watch_time_hours || (Number(stats?.watch_time_seconds || 0) / 3600)); const subProgress = Math.min(100, Math.round((subscribers / thresholds.subscribers) * 100)); const watchProgress = Math.min(100, Math.round((hours / thresholds.watch_hours) * 100)); const eligible = subProgress >= 100 && watchProgress >= 100
  useEffect(() => { let active = true; (async () => { const { data: config } = await supabase.from('admin_settings').select('value').eq('key', 'monetization_thresholds').maybeSingle(); const c = config?.value as Record<string, unknown> | null; if (active && c) setThresholds({ subscribers: Number(c.subscribers || 200), watch_hours: Number(c.watch_hours || 500) }); const { data: profile } = await supabase.from('profiles').select('monetization_status').eq('id', userId).maybeSingle(); const { data: app } = await supabase.from('monetization_applications').select('status').eq('creator_id', userId).order('created_at', { ascending: false }).limit(1).maybeSingle(); if (active) { setStatus(String(profile?.monetization_status || 'not_eligible')); setApplication(app?.status ? String(app.status) : null) } })().catch(() => undefined); return () => { active = false } }, [userId])
  const apply = async () => { if (!eligible) return; setMessage(''); const { data: user } = await supabase.auth.getUser(); if (!user.user) { setMessage('Please sign in again.'); return } const { error } = await supabase.from('monetization_applications').insert({ creator_id: userId, subscribers_at_application: subscribers, watch_time_seconds_at_application: Math.round(hours * 3600), status: 'submitted', checks: { automated_checks: 'queued' } }); if (error) setMessage(error.message); else { setStatus('submitted'); setApplication('submitted'); setMessage('Application submitted for automated checks and review. Approval is not guaranteed.') } }
  return <section className="studio-card"><div className="section-heading"><div><span className="eyebrow"><CheckCircle2 size={14} /> Creator monetization</span><h2>Eligibility and review</h2></div><span className={`status-badge status-${status}`}>{status.replace('_', ' ')}</span></div><div className="stats-grid compact"><div className="stat-card"><Users size={18} /><div><span className="stat-value">{subscribers}</span><span className="stat-label">Current subscribers / {thresholds.subscribers}</span></div></div><div className="stat-card"><Clock3 size={18} /><div><span className="stat-value">{hours.toFixed(1)}h</span><span className="stat-label">Watch time / {thresholds.watch_hours}h</span></div></div></div><div className="progress-item"><div className="progress-label"><span>Subscribers</span><span>{subProgress}%</span></div><div className="progress-bar-track"><div className="progress-bar-fill" style={{ width: `${subProgress}%` }} /></div></div><div className="progress-item"><div className="progress-label"><span>Watch time</span><span>{watchProgress}%</span></div><div className="progress-bar-track"><div className="progress-bar-fill" style={{ width: `${watchProgress}%` }} /></div></div><p className="muted">Thresholds are configurable by Admin and may change. Monetization activates only after checks and approval.</p>{application ? <p className="form-success">Application status: {application.replace('_', ' ')}</p> : <button className="btn-primary" disabled={!eligible} onClick={apply}>{eligible ? 'Apply for review' : 'Keep building toward eligibility'}</button>}{message && <p className="form-error">{message}</p>}</section>
}
