import { useEffect, useState } from 'react'
import { WalletCards } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Props = { userId: string }
export default function WithdrawalSystem({ userId }: Props) { const [balance, setBalance] = useState(0); const [amount, setAmount] = useState(''); const [method, setMethod] = useState('jazzcash'); const [destination, setDestination] = useState(''); const [history, setHistory] = useState<Array<{ id: string; amount: number; status: string; method: string }>>([]); const [message, setMessage] = useState('')
  useEffect(() => { (async () => { const { data: wallet } = await supabase.from('creator_wallets').select('available_balance').eq('creator_id', userId).maybeSingle(); setBalance(Number(wallet?.available_balance || 0)); const { data } = await supabase.from('withdrawal_requests').select('id,amount,status,method').eq('creator_id', userId).order('created_at', { ascending: false }).limit(10); setHistory((data || []) as typeof history) })().catch(() => undefined) }, [userId])
  const request = async () => { const value = Number(amount); if (!value || value <= 0 || value > balance || !destination.trim()) { setMessage('Enter a valid amount within your balance and a verified payout destination.'); return } const { error } = await supabase.from('withdrawal_requests').insert({ creator_id: userId, amount: value, method, payout_details: { destination: destination.trim() }, verification_status: 'required' }); if (error) setMessage(error.message); else { setMessage('Withdrawal request received. It remains pending until verification and review.'); setAmount(''); setDestination('') } }
  return <section className="studio-card"><div className="section-heading"><div><span className="eyebrow"><WalletCards size={14} /> Creator wallet</span><h2>Withdraw available earnings</h2></div><strong className="wallet-balance">PKR {balance.toFixed(2)}</strong></div><div className="form-grid"><label className="form-field"><span>Amount</span><input type="number" min="1" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" /></label><label className="form-field"><span>Payout method</span><select value={method} onChange={e => setMethod(e.target.value)}><option value="jazzcash">JazzCash</option><option value="easypaisa">Easypaisa</option><option value="bank_transfer">Bank transfer</option><option value="card_provider">Card/payment provider</option></select></label><label className="form-field full"><span>Verified payout destination</span><input value={destination} onChange={e => setDestination(e.target.value)} placeholder="Account or IBAN; stored as restricted payout data" /></label></div><button className="btn-primary" onClick={request}>Request withdrawal</button>{message && <p className={message.startsWith('Withdrawal') ? 'form-success' : 'form-error'}>{message}</p>}<div className="studio-table"><div className="table-header"><span>Amount</span><span>Method</span><span>Status</span></div>{history.map(item => <div className="table-row" key={item.id}><span>PKR {Number(item.amount).toFixed(2)}</span><span>{item.method}</span><span>{item.status}</span></div>)}</div></section>
}
