import { useEffect, useState } from 'react'
import { Check, ShieldCheck, Sparkles } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { PREMIUM_MONTHLY_PRICE, startPayFastCheckout } from '../../lib/payfast'

type Props = { userId: string; onRefresh?: () => void }
const features = ['Higher quality where source supports it', 'Higher upload and download limits subject to provider limits', 'Advanced thumbnails and analytics', 'Premium creator tools and AI limits', 'Premium badge and ad-free experience where implemented']
export async function isPremiumUser(userId: string) { const { data } = await supabase.from('premium_subscriptions').select('id').eq('user_id', userId).eq('status', 'active').gt('expires_at', new Date().toISOString()).maybeSingle(); return Boolean(data) }
export default function PremiumSystem({ userId, onRefresh }: Props) {
  const [premium, setPremium] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { isPremiumUser(userId).then(setPremium).catch(() => setPremium(false)) }, [userId])
  const upgrade = async () => { setBusy(true); setMessage(''); const result = await startPayFastCheckout('premium', PREMIUM_MONTHLY_PRICE); if (result.error) setMessage(result.error); else if (result.simulated) setMessage('DEVELOPMENT/SIMULATION mode: no real payment was processed.'); else if (result.checkoutUrl) window.location.assign(result.checkoutUrl); setBusy(false); onRefresh?.() }
  return <section className="studio-card premium-system"><div className="premium-system-header"><div><span className="eyebrow"><Sparkles size={14} /> HkTube Premium</span><h2>{premium ? 'Premium is active' : 'Choose the creator plan that fits you'}</h2><p>{premium ? 'Your account has access to premium features subject to actual provider limits.' : 'Upgrade for more creator capability without promising unsupported quality or storage.'}</p></div>{premium && <span className="creator-badge"><ShieldCheck size={14} /> Premium</span>}</div><div className="premium-tier-grid"><div className="premium-tier"><h3>Free</h3><p>Standard viewing, uploads, ads where configured, and creator tools.</p><span className="tier-price">PKR 0</span></div><div className={`premium-tier featured ${premium ? 'active' : ''}`}><h3>Premium</h3><p>More limits and tools, always subject to source, storage, encoding, and provider support.</p><span className="tier-price">PKR {PREMIUM_MONTHLY_PRICE}<small>/month</small></span><button className="btn-primary" onClick={upgrade} disabled={busy || premium}>{premium ? 'Active' : busy ? 'Preparing…' : 'Upgrade securely'}</button></div></div><div className="feature-list">{features.map(feature => <div key={feature}><Check size={16} />{feature}</div>)}</div>{message && <p className="form-success">{message}</p>}</section>
}
