import { HkTubeShell } from "@/components/HkTubeShell";
import { Button } from "@/components/ui/button";
import { CheckCircle2, ExternalLink, Info, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const clientId = import.meta.env.VITE_ADSENSE_CLIENT_ID as string | undefined;
const hasClient = Boolean(clientId?.startsWith("ca-pub-"));

export default function AdSettings() {
  return <HkTubeShell title="Advertising & AdSense" subtitle="HkTube is prepared for Google AdSense; approval and publisher credentials remain controlled by Google."><div className="mx-auto max-w-4xl space-y-5">
    <section className="rounded-3xl border border-neutral-200 bg-white p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-11 place-items-center rounded-2xl bg-black text-white"><ShieldCheck className="size-5" /></span><div><h2 className="text-xl font-bold">AdSense integration status</h2><p className="mt-1 text-sm text-neutral-500">{hasClient ? "Publisher ID detected in the production build environment." : "Integration is ready, but no AdSense publisher ID is configured yet."}</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Status label="AdSense code" ok={hasClient} /><Status label="Responsive ad units" ok={hasClient} /><Status label="ads.txt file" ok={true} /></div></section>
    <section className="rounded-3xl border border-neutral-200 bg-white p-6 sm:p-8"><div className="flex gap-3"><Info className="mt-1 size-5 shrink-0" /><div><h2 className="font-bold">What is already in HkTube</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-neutral-600"><li>• AdSense loader and responsive ad component are built into the app.</li><li>• A homepage ad placement is ready for a real ad slot.</li><li>• Privacy, cookies, advertising and community-policy pages are available for site review.</li><li>• robots.txt and sitemap.xml are published for crawlers.</li><li>• ads.txt is present without inventing a publisher ID.</li></ul></div></div></section>
    <section className="rounded-3xl border border-neutral-200 bg-neutral-50 p-6 sm:p-8"><h2 className="font-bold">Activation checklist</h2><ol className="mt-3 space-y-3 text-sm leading-6 text-neutral-600"><li><b>1.</b> Add hktube.vercel.app to your Google AdSense Sites list and request review.</li><li><b>2.</b> Put your real publisher ID in Vercel as <code className="rounded bg-white px-1.5 py-0.5">VITE_ADSENSE_CLIENT_ID</code>.</li><li><b>3.</b> Add your real ad unit slot as <code className="rounded bg-white px-1.5 py-0.5">VITE_ADSENSE_HOME_SLOT</code> if you want the fixed homepage unit.</li><li><b>4.</b> Replace the placeholder in <code className="rounded bg-white px-1.5 py-0.5">/ads.txt</code> with the exact line Google gives your account.</li></ol><div className="mt-6 flex flex-wrap gap-3"><Button asChild className="bg-black text-white"><a href="https://www.google.com/adsense/" target="_blank" rel="noreferrer">Open Google AdSense <ExternalLink className="ml-2 size-4" /></a></Button><Button asChild variant="outline"><Link href="/privacy">Privacy policy</Link></Button><Button asChild variant="outline"><Link href="/cookies">Cookies</Link></Button></div></section>
  </div></HkTubeShell>;
}
function Status({ label, ok }: { label: string; ok: boolean }) { return <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4"><div className="flex items-center gap-2 text-sm font-bold"><CheckCircle2 className={`size-4 ${ok ? "text-black" : "text-neutral-400"}`} />{label}</div><p className="mt-1 text-xs text-neutral-500">{ok ? "Ready" : "Needs publisher ID"}</p></div>; }
