import { HkTubeShell } from "@/components/HkTubeShell";
import { ArrowLeft, Cookie, FileText, Megaphone, Scale, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";

type LegalKind = "privacy" | "terms" | "cookies" | "community" | "advertising";
type LegalSection = { heading: string; paragraphs: string[]; bullets?: string[] };

const pages: Record<LegalKind, { icon: typeof FileText; label: string; title: string; intro: string; sections: LegalSection[] }> = {
  privacy: {
    icon: ShieldCheck, label: "Privacy", title: "Privacy Policy", intro: "This policy explains the data HkTube processes for accounts, video publishing, safety, support, personalization, and advertising.",
    sections: [
      { heading: "Controller and contact", paragraphs: ["HkTube is operated by the service owner identified on the Impressum page. Privacy, access, deletion, copyright, safety, and platform-support requests can be sent to hanifnazamdin17@gmail.com."] },
      { heading: "Information we process", paragraphs: ["Depending on the features you use, HkTube may process account identifiers, name, email address, profile information, authentication/session data, channel details, uploaded media metadata, thumbnails, captions, comments, reports, notifications, and activity needed to operate the service. Technical request and security information may also be processed to prevent abuse and keep the service reliable."] },
      { heading: "Why we use it", paragraphs: ["We use information to authenticate users, provide playback and publishing, operate channels and creator tools, maintain requested libraries and notifications, moderate content, investigate reports, prevent fraud and abuse, secure the service, provide support, and comply with legal obligations. Personalization is limited to platform features and saved preferences unless a separate lawful basis applies."] },
      { heading: "Google AdSense advertising", paragraphs: ["HkTube uses Google AdSense on selected public discovery pages. The current HkTube integration requests non-personalized ads rather than behaviorally personalized ads. Google may still use cookies or similar storage for frequency capping, aggregated reporting, and fraud prevention, subject to Google's policies and applicable law. Advertising requests are gated behind HkTube's advertising choice control. Google also requires publishers to disclose its advertising technologies and provide appropriate privacy choices."] },
      { heading: "Personalized advertising", paragraphs: ["This HkTube build does not request personalized AdSense advertising. If personalized publisher advertising is introduced later, the site will update this policy and implement the consent-management requirements applicable to the user's region before doing so. In the EEA, UK, and Switzerland, Google requires a Google-certified consent-management platform integrated with the IAB Europe Transparency and Consent Framework for personalized publisher ads."] },
      { heading: "Your choices and rights", paragraphs: ["Depending on applicable law, you may have rights to access, correct, delete, restrict, object to, or receive a copy of personal data, and to withdraw consent where processing is based on consent. HkTube applies a global human-rights and child-safety baseline and adds jurisdiction-specific safeguards where applicable. Users may also clear local storage through their browser. Requests are assessed for identity and legal/security limits. Users in the EU/EEA may have the right to complain to a competent supervisory authority."] },
      { heading: "Retention and security", paragraphs: ["HkTube retains information only for as long as reasonably necessary for the service, safety, legal obligations, dispute handling, and legitimate operational records. Security controls include authenticated access, server-side authorization, controlled publishing actions, and protected infrastructure. No online service can guarantee absolute security."] },
      { heading: "Third-party services", paragraphs: ["HkTube may rely on infrastructure and service providers such as Supabase, Vercel, Google AdSense, and media-storage providers to operate requested features. The relevant provider may process technical information under its own terms and privacy documentation. HkTube does not sell account information as a product."] },
    ],
  },
  terms: {
    icon: Scale, label: "Terms", title: "Terms of Use", intro: "These terms govern viewing, publishing, accounts, moderation, advertising, and future platform features.",
    sections: [
      { heading: "Using HkTube", paragraphs: ["You must use HkTube lawfully, respect other users, and follow the Community Guidelines. Features may evolve, be rate-limited, suspended, or retired for security, maintenance, legal, or product reasons."] },
      { heading: "Accounts and creator responsibility", paragraphs: ["You are responsible for activity performed through your account and for keeping access secure. Creators are responsible for the legality, accuracy, and rights associated with their videos, clips, thumbnails, captions, posts, and other uploads."] },
      { heading: "Content rights and copyright", paragraphs: ["Only upload content you own or are authorized to distribute. HkTube may restrict or remove content when required by law, these terms, safety rules, or a valid rights complaint. A moderation decision may include a reason and, where the applicable law requires it, an appeal or review path."] },
      { heading: "Advertising and commercial communication", paragraphs: ["Ads are clearly identified as advertising. Paid promotions, sponsorships, affiliate relationships, or commercial communications must be disclosed accurately. Advertising rules never override applicable privacy or consumer-protection law."] },
      { heading: "Enforcement and appeals", paragraphs: ["HkTube may warn, restrict, remove, suspend, or terminate access for violations or security risks. Where a content or account decision is appealable, the decision notice should explain the reason and available review path. HkTube does not promise a fixed moderation time unless expressly stated."] },
    ],
  },
  cookies: {
    icon: Cookie, label: "Cookies", title: "Cookie Notice", intro: "HkTube separates essential storage from optional advertising technology and keeps advertising requests disabled until a choice is made.",
    sections: [
      { heading: "Essential storage", paragraphs: ["HkTube may use cookies, session mechanisms, or local storage that are strictly necessary for authentication, security, preferences, routing, or core requested functions. These technologies can be necessary for the service to work."] },
      { heading: "Advertising storage", paragraphs: ["Google AdSense is loaded only on selected public discovery surfaces after the visitor chooses Allow ads. The current ad requests are marked non-personalized. Non-personalized ads do not use past behavior for ad targeting, but Google states that cookies or mobile identifiers can still be used for frequency capping and aggregated reporting; consent is therefore required where applicable under local law."] },
      { heading: "Personalized advertising", paragraphs: ["HkTube does not request personalized publisher ads in the current integration. If that changes, HkTube will add the required regional consent-management configuration and update this notice before enabling it."] },
      { heading: "Changing your choice", paragraphs: ["Open Settings → Advertising & AdSense to switch between Essential only and Allow ads. You can also clear browser storage to reset local preferences. Clearing storage can sign you out or remove other local preferences."] },
    ],
  },
  community: {
    icon: UsersRound, label: "Community", title: "Community Guidelines", intro: "HkTube is a user-generated video platform built around lawful, respectful, original and rights-cleared content.",
    sections: [
      { heading: "Allowed use", paragraphs: ["Publish content that you have the right to share and describe it accurately. Respect privacy, intellectual-property rights, and the safety of other people."] },
      { heading: "Not allowed", paragraphs: ["Do not use HkTube for illegal content, credible threats, harassment, hateful abuse, exploitation, privacy violations, malware, scams, deceptive impersonation, non-consensual intimate material, or content that materially facilitates serious harm."], bullets: ["Do not upload copyrighted or licensed material without the necessary rights.", "Do not fabricate views, followers, creator identities, endorsements, or engagement.", "Do not target minors with harmful, exploitative, or inappropriate material.", "Do not use HkTube to collect or expose sensitive personal information without a lawful reason and appropriate safeguards."] },
      { heading: "Reports, moderation and appeals", paragraphs: ["Users can report suspected violations through the platform reporting controls and can block other users. HkTube may review reports using human or automated tools. Prohibited content is removed as per applicable laws including PTA Rules, with urgent handling for serious safety matters. HkTube uses a global safety baseline informed by UN human-rights and child-rights principles, while applicable local law can add stricter requirements. If content is restricted or removed, HkTube aims to provide a clear reason and an available review or appeal route where required by applicable law. Repeated abuse of reporting or platform tools may itself be restricted."] },
      { heading: "Safety contact", paragraphs: ["For urgent safety, privacy, copyright, or legal concerns, contact hanifnazamdin17@gmail.com and include the relevant URL and a concise explanation. Do not send passwords or unnecessary sensitive information. Jurisdiction-specific requests are assessed under the law that applies to the service and the requester."] },
    ],
  },
  advertising: {
    icon: Megaphone, label: "Advertising", title: "Advertising Disclosure", intro: "HkTube uses a consent-gated Google AdSense integration on selected public discovery pages.",
    sections: [
      { heading: "Current status", paragraphs: ["HkTube has an AdSense publisher configuration and an ads.txt authorization file. The browser does not request advertising until the visitor chooses Allow ads. Google may still withhold ads, limit fill, or require site review; code alone does not guarantee approval or revenue."] },
      { heading: "Google AdSense", paragraphs: ["The current implementation uses Google AdSense display units and requests non-personalized ads. Google states that non-personalized ads are selected from contextual information rather than the user's past behavior, but cookies or mobile identifiers can still be used for frequency capping and aggregate reporting where permitted. HkTube's privacy and cookie pages disclose this processing."] },
      { heading: "EEA, UK and Switzerland", paragraphs: ["HkTube does not request personalized publisher advertising in this build. If personalized ads are introduced, HkTube will use the required Google-certified consent-management approach for the EEA, UK, and Switzerland and will update the consent and privacy disclosures before activation."] },
      { heading: "Ad placement and destination quality", paragraphs: ["Ads are placed away from controls and are not presented as navigation, download buttons, or misleading content. HkTube will not encourage accidental clicks or use pop-ups/pop-unders for ads. Paid campaigns pointing to HkTube must lead to working, useful destinations with meaningful original value."] },
      { heading: "Transparency", paragraphs: ["Advertising is labelled and kept separate from ordinary navigation. HkTube does not sell advertising based on private account information and does not use ads to collect passwords, payment-card details, or other personal information."] },
    ],
  },
};

export function LegalPage({ kind }: { kind: LegalKind }) {
  const page = pages[kind];
  const Icon = page.icon;
  return <HkTubeShell>
    <article className="mx-auto max-w-3xl pb-10 pt-1"><Link href="/settings" className="inline-flex items-center text-sm font-semibold text-fuchsia-200 hover:text-fuchsia-100"><ArrowLeft className="mr-1.5 size-4" />Back to settings</Link><div className="mt-6 rounded-3xl border border-violet-300/18 bg-gradient-to-br from-violet-500/[.12] via-fuchsia-500/[.045] to-cyan-400/[.06] p-6 sm:p-8"><span className="grid size-12 place-items-center rounded-2xl bg-violet-500/15 text-violet-100"><Icon className="size-6" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-fuchsia-200">HKTUBE {page.label}</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">{page.title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300">{page.intro}</p><p className="mt-5 text-xs text-slate-500">Last updated: 13 September 2026</p></div><div className="mt-8 space-y-8">{page.sections.map(section => <section key={section.heading}><h2 className="text-xl font-bold text-white">{section.heading}</h2>{section.paragraphs.map(paragraph => <p key={paragraph} className="mt-3 text-sm leading-7 text-slate-400">{paragraph}</p>)}{section.bullets && <ul className="mt-4 space-y-2 rounded-2xl border border-white/8 bg-white/[.025] p-5 text-sm leading-6 text-slate-400">{section.bullets.map(bullet => <li key={bullet} className="flex gap-2"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-fuchsia-300" />{bullet}</li>)}</ul>}</section>)}</div></article>
  </HkTubeShell>;
}
