import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { HkTubeShell } from "@/components/HkTubeShell";
import { Button } from "@/components/ui/button";
import { ArrowRight, BarChart3, BookOpen, CircleUserRound, Clapperboard, Clock3, Download, Gift, Grid2X2, LogOut, Radio, Settings, ShieldCheck, Sparkles, UserRound, Wallet } from "lucide-react";
import { Link } from "wouter";

export default function Menu() {
  const { user, loading, logout } = useAuth();
  if (loading) return <HkTubeShell title="Menu"><div className="grid min-h-[55vh] place-items-center"><CircleUserRound className="size-8 animate-pulse text-fuchsia-300" /></div></HkTubeShell>;
  if (!user) return <HkTubeShell title="Menu"><section className="mx-auto max-w-md pt-6 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-fuchsia-500/15 text-fuchsia-200"><CircleUserRound className="size-7" /></span><h1 className="mt-5 text-3xl font-bold text-white">Account details</h1><p className="mt-3 text-sm leading-6 text-slate-400">Sign in to access your profile, library, subscriptions, and creator tools.</p><Button onClick={startLogin} className="mt-6 bg-gradient-to-r from-violet-500 to-fuchsia-500 font-bold text-white">Sign in to HKTUBE</Button></section></HkTubeShell>;
  const initial = (user.name || "H").slice(0, 1).toUpperCase();
  return <HkTubeShell title="Menu"><div className="mx-auto max-w-6xl space-y-7">
    <section><p className="mb-3 px-1 text-xs font-bold uppercase tracking-[.18em] text-fuchsia-300">Account Details</p><div className="rounded-3xl border border-white/10 bg-gradient-to-r from-white/[.09] to-violet-400/[.08] p-5 sm:p-6"><div className="flex items-center gap-4"><span className="grid size-16 place-items-center rounded-full border-2 border-fuchsia-300/60 bg-violet-500/35 text-2xl font-black text-white">{initial}</span><div><h2 className="text-xl font-bold text-white">{user.name || "HKTUBE member"}</h2><p className="mt-1 flex items-center gap-1 text-sm text-slate-300">{user.role === "admin" ? "Creator account" : "Viewer account"}<ShieldCheck className="size-4 text-fuchsia-300" /></p>{user.email && <p className="mt-1 text-xs text-slate-500">{user.email}</p>}</div></div><p className="mt-5 border-t border-white/10 pt-4 text-sm text-slate-400">Followed creators and account activity appear here from your authenticated HkTube account.</p></div></section>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><section><p className="mb-3 px-1 text-xs font-bold uppercase tracking-[.18em] text-fuchsia-300">Profile account options</p><div className="grid gap-3 sm:grid-cols-2"><MenuTile href="/profile" icon={UserRound} title="My Channel" /><MenuTile href="/studio" icon={Clapperboard} title="HKTUBE Studio" /><MenuTile href="/subscriptions" icon={BookOpen} title="Subscriptions" /><MenuTile href="/settings" icon={Settings} title="Settings" /><MenuTile href="/history" icon={Clock3} title="Time Watched" /><MenuTile href="/library" icon={Wallet} title="Purchases & Memberships" /><MenuTile href="/menu" icon={Grid2X2} title="Switch Account" /><button onClick={() => void logout()} className="flex items-center gap-3 rounded-2xl border border-white/9 bg-white/[.025] p-4 text-left hover:border-fuchsia-300/25"><LogOut className="size-5 text-slate-300" /><span className="font-semibold text-white">Sign Out</span></button><MenuTile href="/library" icon={Download} title="Downloaded Videos" /></div></section><section><p className="mb-3 px-1 text-xs font-bold uppercase tracking-[.18em] text-fuchsia-300">HKTUBE Creator Studio Overview</p><div className="grid gap-3 sm:grid-cols-2"><StudioTile icon={Sparkles} title="Mini-AI Studio Assistant" description="Guidance for creator tools" /><StudioTile icon={BarChart3} title="Channel Dashboard" description="Analytics from real records" /><StudioTile icon={Clapperboard} title="Content Manager" description="Manage videos and live" /><StudioTile icon={BookOpen} title="Comments & Community" description="Review your conversations" /><StudioTile icon={Wallet} title="Monetization Tools" description="Coins, gifts, and payouts" /><StudioTile icon={Settings} title="Customization & SEO" description="Channel settings and metadata" /></div></section></div>
    <div className="grid gap-6 lg:grid-cols-2"><section><p className="mb-3 px-1 text-xs font-bold uppercase tracking-[.18em] text-fuchsia-300">Creator Studio</p><div className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-center gap-3"><Gift className="size-5 text-fuchsia-300" /><div><h2 className="font-bold text-white">Monetization & gifting</h2><p className="mt-1 text-sm text-slate-400">Only confirmed transactions and configured providers are shown.</p></div></div><Link href="/studio" className="mt-5 inline-flex items-center text-sm font-semibold text-fuchsia-200">Open Creator Studio <ArrowRight className="ml-1.5 size-4" /></Link></div></section><section><p className="mb-3 px-1 text-xs font-bold uppercase tracking-[.18em] text-fuchsia-300">Studio tools & analytics</p><div className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="grid gap-3 sm:grid-cols-2"><StudioTile icon={BarChart3} title="Analytics" description="Views and engagement" /><StudioTile icon={Radio} title="Live" description="Discover live sessions" /></div></div></section></div>
  </div></HkTubeShell>;
}
function MenuTile({ href, icon: Icon, title }: { href: string; icon: typeof UserRound; title: string }) { return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-white/9 bg-white/[.025] p-4 transition hover:border-fuchsia-300/25 hover:bg-white/[.05]"><Icon className="size-5 text-fuchsia-200" /><span className="font-semibold text-white">{title}</span><ArrowRight className="ml-auto size-4 text-slate-600" /></Link>; }
function StudioTile({ icon: Icon, title, description }: { icon: typeof Sparkles; title: string; description: string }) { return <div className="rounded-2xl border border-white/8 bg-white/[.035] p-4"><Icon className="size-5 text-violet-300" /><h3 className="mt-3 text-sm font-bold text-white">{title}</h3><p className="mt-1 text-xs text-slate-500">{description}</p></div>; }
