import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { HkTubeShell } from "@/components/HkTubeShell";
import { SupabaseVideoCard } from "@/components/SupabaseVideoCard";
import { supabase } from "@/lib/supabase";
import { Loader2, Lock, Globe2, Trash2 } from "lucide-react";
import { toast } from "sonner";

type Playlist={id:string;owner_id:string;title:string;description:string;visibility:"public"|"unlisted"|"private"};
export default function Playlist(){const [,params]=useRoute("/playlist/:id");const id=params?.id||"";const [playlist,setPlaylist]=useState<Playlist|null>(null);const [items,setItems]=useState<any[]>([]);const [owner,setOwner]=useState(false);const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;const load=async()=>{setLoading(true);const [{data:p,error:pError},{data:{user}}]=await Promise.all([supabase.from("playlists").select("id,owner_id,title,description,visibility").eq("id",id).maybeSingle(),supabase.auth.getUser()]);if(!active)return;if(pError||!p){setPlaylist(null);setLoading(false);return;}setPlaylist(p as Playlist);setOwner(Boolean(user&&user.id===p.owner_id));const {data}=await supabase.from("playlist_items").select("video_id,position,videos(id,title,description,thumbnail_path,duration_seconds,views,published_at,tags)").eq("playlist_id",id).order("position",{ascending:true});if(active)setItems((data??[]).map((x:any)=>x.videos).filter(Boolean));setLoading(false);};void load();return()=>{active=false}},[id]);
 async function remove(videoId:string){if(!owner)return;const {error}=await supabase.from("playlist_items").delete().eq("playlist_id",id).eq("video_id",videoId);if(error)toast.error(error.message);else{setItems(v=>v.filter(x=>x.id!==videoId));toast.success("Removed from playlist.");}}
 async function share(){try{await navigator.clipboard.writeText(window.location.href);toast.success("Playlist link copied.")}catch{toast.error("Could not copy the playlist link.")}}
 if(loading)return <HkTubeShell><div className="grid min-h-[45vh] place-items-center"><Loader2 className="size-8 animate-spin"/></div></HkTubeShell>;
 if(!playlist)return <HkTubeShell title="Playlist unavailable"><div className="mx-auto max-w-xl rounded-3xl border border-white/10 bg-white/[.03] p-10 text-center text-slate-400">This playlist is private, unavailable, or the link is incorrect.</div></HkTubeShell>;
 return <HkTubeShell title={playlist.title}><main className="mx-auto w-full max-w-[1400px] px-4 pb-16 sm:px-8"><section className="mb-7 rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-300">Playlist · {items.length} videos</p><h1 className="mt-1 text-3xl font-black text-white">{playlist.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{playlist.description||"No description."}</p><span className="mt-3 inline-flex items-center gap-1 text-xs text-slate-500">{playlist.visibility==="public"?<Globe2 className="size-3.5"/>:<Lock className="size-3.5"/>}{playlist.visibility}</span></div><div className="flex gap-2"><button onClick={()=>void share()} className="rounded-full border border-white/10 px-4 py-2 text-sm font-bold text-white">Share</button>{owner&&<Link href="/playlists" className="rounded-full border border-white/10 px-4 py-2 text-sm font-bold text-slate-300">Manage</Link>}</div></div></section><div className="grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(v=><div key={v.id} className="relative"><SupabaseVideoCard video={{id:String(v.id),title:v.title,thumbnailUrl:v.thumbnail_path?supabase.storage.from("thumbnails").getPublicUrl(v.thumbnail_path).data.publicUrl:null,durationSeconds:v.duration_seconds,views:v.views,publishedAt:v.published_at,isShort:Array.isArray(v.tags)&&v.tags.includes("shorts")}}/>{owner&&<button onClick={()=>void remove(v.id)} className="absolute right-1 top-1 z-10 grid size-8 place-items-center rounded-full bg-black/70 text-white hover:bg-rose-500/80" aria-label="Remove from playlist"><Trash2 className="size-4"/></button>}</div>)}</div>{!items.length&&<div className="rounded-3xl border border-dashed border-white/10 p-12 text-center text-slate-500">This playlist has no videos yet. Add videos from a watch page.</div>}</main></HkTubeShell>;
}
