import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { HkTubeShell } from "@/components/HkTubeShell";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { ArrowRight, BadgeCheck, Bot, Captions, Cookie, FileText, Gauge, Globe2, KeyRound, Loader2, LogOut, Mail, Megaphone, Moon, Palette, Play, Scale, Settings2, ShieldCheck, Sparkles, UserRound, Wallet, UsersRound } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { Link } from "wouter";

const policyLinks = [
  { href: "/privacy", icon: ShieldCheck, title: "Privacy Policy", description: "How account and video data is handled" },
  { href: "/terms", icon: Scale, title: "Terms of Use", description: "Rules for using HkTube" },
  { href: "/cookies", icon: Cookie, title: "Cookie Notice", description: "Essential session and preference cookies" },
  { href: "/community", icon: UsersRound, title: "Community Guidelines", description: "Rules for uploaded and shared content" },
  { href: "/advertising", icon: Megaphone, title: "Advertising Disclosure", description: "Advertising consent and disclosure information" },
  { href: "/contact", icon: Mail, title: "Contact Us", description: "Privacy, content, and platform support" },
  { href: "/about", icon: FileText, title: "About HkTube", description: "What HkTube is and how the platform works" },
];

export default function Settings() {
  const { user, loading, logout } = useAuth();
  const [familyMode, setFamilyMode] = useState(false);
  const [autoplay, setAutoplay] = useState(true);
  const [dataSaver, setDataSaver] = useState(false);
  const [captions, setCaptions] = useState(false);
  const [notifications, setNotifications] = useState(true);
  const [quality, setQuality] = useState("auto");
  const [language, setLanguage] = useState("English");
  useEffect(() => { setFamilyMode(localStorage.getItem("hktube-family-mode") === "enabled"); setAutoplay(localStorage.getItem("hktube-autoplay") !== "disabled"); setDataSaver(localStorage.getItem("hktube-data-saver") === "enabled"); setCaptions(localStorage.getItem("hktube-captions") === "enabled"); setNotifications(localStorage.getItem("hktube-notifications") !== "disabled"); setQuality(localStorage.getItem("hktube-playback-quality") || "auto"); setLanguage(localStorage.getItem("hktube-language") || "English"); }, []);
  function save(key: string, value: string) { localStorage.setItem(key, value); }
  function bool(key: string, value: boolean, setter: (value: boolean) => void) { setter(value); save(key, value ? "enabled" : "disabled"); }
  if (loading) return <HkTubeShell title="Settings"><div className="grid min-h-[55vh] place-items-center"><Loader2 className="size-7 animate-spin text-fuchsia-300" /></div></HkTubeShell>;
  return <HkTubeShell title="Settings" subtitle="Manage your HkTube account, playback, privacy, creator tools and app preferences."><div className="mx-auto max-w-3xl space-y-7 px-4 pb-10 sm:px-0">
    <section className="rounded-3xl border border-violet-300/18 bg-gradient-to-br from-violet-500/[.14] via-fuchsia-500/[.05] to-cyan-400/[.06] p-5 sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid size-16 shrink-0 place-items-center rounded-full border border-fuchsia-300/40 bg-fuchsia-500/15 text-xl font-black text-fuchsia-50">{(user?.name || "G").slice(0, 1).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[.18em] text-fuchsia-200">Account & identity</p><h2 className="mt-2 truncate text-xl font-black text-white">{user?.name || "Guest viewer"}</h2><p className="mt-1 truncate text-sm text-slate-300">{user?.email || "Your preferences can be used now; sign in to sync account data."}</p><span className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-cyan-200"><BadgeCheck className="size-3.5" />{user ? (user.role === "admin" ? "Owner access" : "HkTube member") : "Guest preferences"}</span></div><div className="flex flex-wrap gap-2">{user ? <><Link href="/profile" className="rounded-full bg-white px-4 py-2 text-sm font-bold text-slate-950">View channel</Link><Button variant="ghost" onClick={() => void logout()} className="border border-white/10 text-slate-300 hover:bg-white/5 hover:text-white"><LogOut className="mr-2 size-4" />Sign out</Button></> : <Button onClick={startLogin} className="rounded-full bg-gradient-to-r from-violet-500 to-fuchsia-500 font-bold text-white">Sign in / Sign up</Button>}</div></div></section>
    <SettingsGroup title="Playback & accessibility" icon={Play}><SettingRow title="Autoplay Shorts" description="Starts a real Short when it enters the full-screen viewer." control={<Switch checked={autoplay} onCheckedChange={value => bool("hktube-autoplay", value, setAutoplay)} aria-label="Enable Shorts autoplay" />} /><SettingRow title="Preferred quality" description="Saved on this device and used when a published video offers multiple renditions." control={<select value={quality} onChange={event => { setQuality(event.target.value); save("hktube-playback-quality", event.target.value); }} className="rounded-xl border border-white/10 bg-[#151a25] px-3 py-2 text-sm font-semibold text-white outline-none focus:border-violet-300"><option value="auto">Auto</option><option value="1080p">1080p</option><option value="720p">720p HD</option><option value="480p">480p</option><option value="360p">360p</option></select>} /><SettingRow title="Captions by default" description="Remember your caption preference for videos that provide a real caption track." control={<Switch checked={captions} onCheckedChange={value => bool("hktube-captions", value, setCaptions)} aria-label="Enable captions by default" />} /></SettingsGroup>
    <SettingsGroup title="Data & notifications" icon={Gauge}><SettingRow title="Reduce media preload" description="Load metadata first to reduce mobile data use. This does not alter uploaded media." control={<Switch checked={dataSaver} onCheckedChange={value => bool("hktube-data-saver", value, setDataSaver)} aria-label="Enable data saving" />} /><SettingRow title="Activity notifications" description="Enable the local preference for HkTube activity notices. Delivery requires a configured notification provider." control={<Switch checked={notifications} onCheckedChange={value => bool("hktube-notifications", value, setNotifications)} aria-label="Enable notifications" />} /><SettingRow title="Product analytics" description="No third-party product analytics tracker is active in this build." control={<Status text="Not configured" />} /></SettingsGroup>
    <SettingsGroup title="Language, appearance & safety" icon={Palette}><SettingRow title="Language" description="Choose the interface language preference saved on this browser." control={<select value={language} onChange={event => { setLanguage(event.target.value); save("hktube-language", event.target.value); }} className="rounded-xl border border-white/10 bg-[#151a25] px-3 py-2 text-sm font-semibold text-white outline-none"><option>English</option><option>Urdu</option><option>Hindi</option></select>} /><SettingRow title="Theme" description="The current HkTube visual system follows the app theme preference." control={<Link href="/" className="inline-flex items-center gap-1 rounded-full bg-violet-500/15 px-3 py-1.5 text-xs font-bold text-violet-100">Eclipse <ArrowRight className="size-3" /></Link>} /><SettingRow title="Family Mode" description="Hide Shorts and other discovery surfaces on this browser. It is not a replacement for parental supervision." control={<Switch checked={familyMode} onCheckedChange={value => bool("hktube-family-mode", value, setFamilyMode)} aria-label="Enable Family Mode" />} /></SettingsGroup>
    <SettingsGroup title="Creator & advanced tools" icon={Sparkles}><IntegrationRow icon={Wallet} title="Monetization & payouts" description="Revenue sharing, payout identity and tax onboarding require a connected payment provider." href="/studio" /><IntegrationRow icon={Bot} title="AI Creator Tools" description="Subtitles, dubbing, SEO assistance and generation require an enabled AI provider." href="/studio" /><IntegrationRow icon={KeyRound} title="Security & sessions" description="Owner permissions remain enforced server-side. Password reset and email verification require an email provider." href="/auth" /></SettingsGroup>
    <section><p className="px-1 text-xs font-bold uppercase tracking-[.18em] text-slate-500">Policies & help</p><div className="mt-3 space-y-2">{policyLinks.map(item => <SettingsLink key={item.href} {...item} />)}</div></section>
    <section className="rounded-3xl border border-cyan-300/15 bg-cyan-300/[.035] p-5"><div className="flex gap-3"><Globe2 className="mt-0.5 size-5 shrink-0 text-cyan-200" /><div><h2 className="font-bold text-white">Real-data promise</h2><p className="mt-1 text-sm leading-6 text-slate-400">HkTube only shows records returned by its database and connected providers. It does not invent views, subscribers, payouts, AI results or video thumbnails.</p></div></div></section>
  </div></HkTubeShell>;
}
function SettingsGroup({ title, icon: Icon, children }: { title: string; icon: typeof Play; children: ReactNode }) { return <section className="space-y-2"><p className="flex items-center gap-2 px-1 text-xs font-bold uppercase tracking-[.18em] text-slate-500"><Icon className="size-3.5 text-violet-200" />{title}</p>{children}</section>; }
function SettingRow({ title, description, control }: { title: string; description: string; control: ReactNode }) { return <div className="flex items-center justify-between gap-5 rounded-2xl border border-white/9 bg-white/[.025] p-4"><div className="min-w-0"><h2 className="text-sm font-bold text-white">{title}</h2><p className="mt-1 max-w-xl text-xs leading-5 text-slate-400">{description}</p></div><div className="shrink-0">{control}</div></div>; }
function Status({ text }: { text: string }) { return <span className="rounded-full border border-white/10 bg-white/[.035] px-3 py-1.5 text-xs font-semibold text-slate-400">{text}</span>; }
function IntegrationRow({ icon: Icon, title, description, href }: { icon: typeof Wallet; title: string; description: string; href: string }) { return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-white/9 bg-white/[.025] p-4 transition hover:border-violet-300/25 hover:bg-white/[.05]"><span className="grid size-10 place-items-center rounded-xl bg-violet-500/12 text-violet-200"><Icon className="size-4.5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold text-white">{title}</span><span className="mt-0.5 block text-xs leading-5 text-slate-500">{description}</span></span><Status text="Integration required" /><ArrowRight className="size-4 shrink-0 text-slate-500" /></Link>; }
function SettingsLink({ href, icon: Icon, title, description }: { href: string; icon: typeof FileText; title: string; description: string }) { return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-white/9 bg-white/[.025] p-4 transition hover:border-fuchsia-300/25 hover:bg-white/[.05]"><span className="grid size-10 place-items-center rounded-xl bg-violet-500/12 text-violet-200"><Icon className="size-4.5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold text-white">{title}</span><span className="mt-0.5 block text-xs text-slate-500">{description}</span></span><ArrowRight className="size-4 text-slate-500" /></Link>; }
