import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { HkTubeShell } from "@/components/HkTubeShell";
import { SupabaseVideoCard } from "@/components/SupabaseVideoCard";
import { searchPublicVideos } from "@/lib/supabaseEngagement";
import { recordDiscoveryEvent } from "@/lib/supabaseDiscovery";
import { supabase } from "@/lib/supabase";
import { Loader2, Search, Users, Video } from "lucide-react";

export default function SupabaseSearch(){
  const [location]=useLocation();
  const query=new URLSearchParams(location.split("?")[1]||"").get("q")?.trim()||"";
  const [tab,setTab]=useState<"videos"|"channels"|"topics">("videos");
  const [results,setResults]=useState<any[]>([]); const [channels,setChannels]=useState<any[]>([]); const [loading,setLoading]=useState(false);
  useEffect(()=>{if(!query){setResults([]);setChannels([]);return;}let active=true;setLoading(true);void Promise.all([
    searchPublicVideos(query,48),
    supabase.from("channels").select("id,name,handle,description,avatar_url,subscriber_count").or(`name.ilike.%${query}%,handle.ilike.%${query}%`).order("subscriber_count",{ascending:false}).limit(24),
  ]).then(([rows,channelResult])=>{if(active){setResults(rows);setChannels(channelResult.data??[]);void recordDiscoveryEvent({eventType:"search",objectType:"search",context:{query_length:query.length}}).catch(()=>undefined);}}).catch(()=>{if(active){setResults([]);setChannels([]);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query]);
  const topics=useMemo(()=>{const map=new Map<string,number>();results.forEach(v=>(Array.isArray(v.tags)?v.tags:[]).forEach((tag:string)=>{const key=tag.trim();if(key&&key.toLowerCase()!=="shorts")map.set(key,(map.get(key)||0)+1);}));return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,24);},[results]);
  return <HkTubeShell title="Search"><main className="mx-auto w-full max-w-[1480px] px-4 pb-16 sm:px-8 lg:px-10">{query?<>
    <div className="mb-5 flex items-center gap-3"><Search className="size-5 text-violet-300"/><div><p className="text-xs uppercase tracking-[.18em] text-slate-500">Intent search</p><h1 className="text-2xl font-black text-white">Results for “{query}”</h1></div></div>
    <div className="mb-7 flex gap-2 overflow-x-auto [scrollbar-width:none]"><button onClick={()=>setTab("videos")} className={`rounded-full px-4 py-2 text-sm font-bold ${tab==="videos"?"bg-white text-black":"border border-white/10 bg-white/[.04] text-slate-300"}`}><Video className="mr-2 inline size-4"/>Videos {results.length}</button><button onClick={()=>setTab("channels")} className={`rounded-full px-4 py-2 text-sm font-bold ${tab==="channels"?"bg-white text-black":"border border-white/10 bg-white/[.04] text-slate-300"}`}><Users className="mr-2 inline size-4"/>Channels {channels.length}</button><button onClick={()=>setTab("topics")} className={`rounded-full px-4 py-2 text-sm font-bold ${tab==="topics"?"bg-white text-black":"border border-white/10 bg-white/[.04] text-slate-300"}`}>Topics {topics.length}</button></div>
    {loading?<div className="grid min-h-[35vh] place-items-center"><Loader2 className="size-8 animate-spin"/></div>:tab==="videos"?(results.length?<div className="grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{results.map(v=><SupabaseVideoCard key={v.id} video={{id:String(v.id),title:v.title,thumbnailUrl:v.thumbnail_path&&v.thumbnail_path.startsWith("http")?v.thumbnail_path:null,durationSeconds:v.duration_seconds,views:v.views,publishedAt:v.published_at,isShort:Array.isArray(v.tags)&&v.tags.includes("shorts")}}/>)}</div>:<Empty label="No public videos matched your search."/>):tab==="channels"?(channels.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{channels.map(c=><a key={c.id} href={`/channel/${encodeURIComponent(c.handle)}`} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 transition hover:border-violet-400/30 hover:bg-white/[.05]"><div className="flex items-center gap-3"><div className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-full bg-violet-500/20 text-lg font-black text-white">{c.avatar_url?<img src={c.avatar_url} alt="" className="size-full object-cover"/>:(c.name||c.handle||"H").slice(0,1).toUpperCase()}</div><div className="min-w-0"><h2 className="truncate font-bold text-white">{c.name}</h2><p className="truncate text-xs text-slate-500">@{c.handle} · {Number(c.subscriber_count||0).toLocaleString()} followers</p></div></div><p className="mt-3 line-clamp-2 text-sm text-slate-400">{c.description||"HkTube creator"}</p></a>)}</div>:<Empty label="No matching channels."/>):<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{topics.map(([topic,count])=><a key={topic} href={`/search?q=${encodeURIComponent(topic)}`} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 hover:border-violet-400/30"><p className="font-bold text-white">#{topic}</p><p className="mt-1 text-xs text-slate-500">{count} matching videos</p></a>)}{!topics.length&&<Empty label="No indexed topics found in these results."/>}</div>}
  </>:<Empty label="Type something in the search box to find videos, channels and topics."/>}</main></HkTubeShell>
}
function Empty({label}:{label:string}){return <div className="rounded-3xl border border-white/10 bg-white/[.03] p-12 text-center text-slate-400">{label}</div>}
