import { useEffect, useState } from "react";
import { Link } from "wouter";
import { HkTubeShell } from "@/components/HkTubeShell";
import { SupabaseVideoCard } from "@/components/SupabaseVideoCard";
import { supabase } from "@/lib/supabase";
import { Loader2 } from "lucide-react";

function url(bucket:string,path:string|null){return path?(/^https?:\/\//i.test(path)?path:supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl):null;}
export function SupabaseCollections({kind}:{kind:"shorts"|"trending"}){const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{let active=true;setLoading(true);const run=async()=>{const q=supabase.from("videos").select("id,title,thumbnail_path,duration_seconds,views,published_at,tags").eq("visibility","public").eq("status","published");const {data}=kind==="shorts"?await q.contains("tags",["shorts"]).order("published_at",{ascending:false}).limit(40):await q.order("views",{ascending:false}).limit(40);if(active)setItems(data??[]);setLoading(false);};void run();return()=>{active=false;};},[kind]);return <HkTubeShell title={kind==="shorts"?"Shorts":"Trending"}><main className="mx-auto w-full max-w-[1480px] px-4 pb-16 sm:px-8 lg:px-10"><div className="mb-7 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-300">HkTube discovery</p><h1 className="mt-1 text-3xl font-black text-white">{kind==="shorts"?"Shorts":"Trending now"}</h1></div><Link href="/upload?category=shorts" className="rounded-full bg-white px-4 py-2 text-sm font-bold text-black">Create</Link></div>{loading?<div className="grid min-h-[40vh] place-items-center"><Loader2 className="size-8 animate-spin"/></div>:items.length?<div className={kind==="shorts"?"grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5":"grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"}>{items.map(v=><SupabaseVideoCard key={v.id} video={{id:String(v.id),title:v.title,thumbnailUrl:url("thumbnails",v.thumbnail_path),durationSeconds:v.duration_seconds,views:v.views,publishedAt:v.published_at,isShort:kind==="shorts"}}/>)}</div>:<div className="rounded-3xl border border-dashed border-white/10 p-12 text-center text-slate-500">No approved content yet.</div>}</main></HkTubeShell>}
