import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { HkTubeShell } from "@/components/HkTubeShell";
import { SupabaseVideoCard } from "@/components/SupabaseVideoCard";
import { listSavedVideoIds, listWatchHistoryVideoIds } from "@/lib/supabaseEngagement";
import { listMySupabaseVideos } from "@/lib/supabaseVideos";
import { supabase } from "@/lib/supabase";
import { Bell, BarChart3, CheckCheck, Clock3, Heart, Loader2, Plus, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

const titles:any={library:"Your Library",history:"Watch history",subscriptions:"Subscriptions",notifications:"Notifications",playlists:"Playlists",studio:"Creator Studio",posts:"Community posts"};
function media(path:string|null){return path?(path.startsWith("http")?path:supabase.storage.from("thumbnails").getPublicUrl(path).data.publicUrl):null;}
function formatWatch(seconds:number){const s=Math.max(0,Math.floor(seconds));return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`;}

export function SupabasePlatform({kind}:{kind:string}){
  const [userId,setUserId]=useState<string|null>(null); const [items,setItems]=useState<any[]>([]); const [notifications,setNotifications]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [libraryTab,setLibraryTab]=useState<"saved"|"liked">("saved"); const [libraryQuery,setLibraryQuery]=useState(""); const [playlistTitle,setPlaylistTitle]=useState(""); const [creatingPlaylist,setCreatingPlaylist]=useState(false);
  async function load(){setLoading(true);try{const auth=await supabase.auth.getUser();const uid=auth.data.user?.id||null;setUserId(uid);if(!uid){setItems([]);setNotifications([]);return;}
    if(kind==="library"){const ids=libraryTab==="saved"?await listSavedVideoIds():((await supabase.from("likes").select("video_id").eq("user_id",uid).not("video_id","is",null)).data??[]).map(x=>String(x.video_id));if(ids.length){const r=await supabase.from("videos").select("id,title,thumbnail_path,duration_seconds,views,published_at,tags").in("id",ids);const order=new Map(ids.map((id,i)=>[id,i]));setItems((r.data??[]).sort((a,b)=>(order.get(String(a.id))??999)-(order.get(String(b.id))??999)));}else setItems([]);
    } else if(kind==="history"){const ids=await listWatchHistoryVideoIds();if(ids.length){const r=await supabase.from("videos").select("id,title,thumbnail_path,duration_seconds,views,published_at,tags").in("id",ids);const order=new Map(ids.map((id,i)=>[id,i]));setItems((r.data??[]).sort((a,b)=>(order.get(String(a.id))??999)-(order.get(String(b.id))??999)));}else setItems([]);
    } else if(kind==="subscriptions"){const r=await supabase.from("subscriptions").select("channel_id,created_at,channels(id,handle,name,avatar_url,subscriber_count)").eq("subscriber_id",uid).order("created_at",{ascending:false});setItems(r.data??[]);
    } else if(kind==="notifications"){const r=await supabase.from("notifications").select("id,title,body,type,entity_type,entity_id,read_at,created_at").eq("user_id",uid).order("created_at",{ascending:false}).limit(100);setNotifications(r.data??[]);
    } else if(kind==="playlists"){const r=await supabase.from("playlists").select("id,title,description,visibility,created_at,updated_at,playlist_items(count)").eq("owner_id",uid).order("updated_at",{ascending:false});setItems(r.data??[]);
    } else if(kind==="studio"){setItems(await listMySupabaseVideos(uid));
    } else if(kind==="posts"){const r=await supabase.from("posts").select("id,content,media_path,created_at,likes_count").eq("visibility","public").eq("status","published").eq("moderation_status","approved").order("created_at",{ascending:false}).limit(50);setItems(r.data??[]);
    }}catch(e){toast.error(e instanceof Error?e.message:"Could not load this HkTube section.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[kind,userId,libraryTab]);
  useEffect(()=>{if(kind!=="notifications"||!userId)return;const channel=supabase.channel(`hktube-notifications-${userId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications",filter:`user_id=eq.${userId}`},payload=>setNotifications(current=>[payload.new,...current].slice(0,100))).subscribe();return()=>{void supabase.removeChannel(channel);};},[kind,userId]);
  const filteredLibrary=useMemo(()=>items.filter(v=>!libraryQuery.trim()||String(v.title).toLowerCase().includes(libraryQuery.trim().toLowerCase())),[items,libraryQuery]);
  async function markRead(id:string){if(!userId)return;const {error}=await supabase.from("notifications").update({read_at:new Date().toISOString()}).eq("id",id).eq("user_id",userId);if(error)toast.error(error.message);else setNotifications(current=>current.map(n=>n.id===id?{...n,read_at:new Date().toISOString()}:n));}
  async function markAllRead(){if(!userId)return;const {error}=await supabase.from("notifications").update({read_at:new Date().toISOString()}).eq("user_id",userId).is("read_at",null);if(error)toast.error(error.message);else setNotifications(current=>current.map(n=>({...n,read_at:n.read_at||new Date().toISOString()})));}
  async function createPlaylist(){if(!userId)return;const title=playlistTitle.trim();if(!title)return;setCreatingPlaylist(true);const {error}=await supabase.from("playlists").insert({owner_id:userId,title,description:"",visibility:"private"});setCreatingPlaylist(false);if(error)toast.error(error.message);else{setPlaylistTitle("");toast.success("Playlist created.");await load();}}
  async function deletePlaylist(id:string){if(!userId)return;const {error}=await supabase.from("playlists").delete().eq("id",id).eq("owner_id",userId);if(error)toast.error(error.message);else{setItems(current=>current.filter(p=>p.id!==id));toast.success("Playlist deleted.");}}
  if(loading)return <HkTubeShell title={titles[kind]||"HkTube"}><div className="grid min-h-[45vh] place-items-center"><Loader2 className="size-8 animate-spin"/></div></HkTubeShell>;
  if(!userId)return <HkTubeShell title={titles[kind]||"HkTube"}><main className="mx-auto max-w-3xl px-4 pb-16"><div className="rounded-3xl border border-white/10 bg-white/[.03] p-12 text-center text-slate-400">Sign in to use {titles[kind]?.toLowerCase()||"this feature"}.</div></main></HkTubeShell>;
  return <HkTubeShell title={titles[kind]||"HkTube"}><main className="mx-auto w-full max-w-[1400px] px-4 pb-16 sm:px-8">
    {kind==="notifications"?<section><div className="mb-5 flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-300">Activity center</p><h1 className="text-2xl font-black text-white">Notifications</h1></div><Button variant="outline" onClick={()=>void markAllRead()}><CheckCheck className="mr-2 size-4"/>Mark all read</Button></div><div className="space-y-3">{notifications.map(n=><article key={n.id} className={`rounded-2xl border p-4 ${n.read_at?"border-white/8 bg-white/[.02]":"border-violet-400/20 bg-violet-500/[.06]"}`}><div className="flex gap-3"><Bell className="mt-1 size-4 text-violet-300"/><div className="min-w-0 flex-1"><h3 className="font-bold text-white">{n.title}</h3><p className="mt-1 text-sm text-slate-400">{n.body}</p><p className="mt-2 text-xs text-slate-600">{new Date(n.created_at).toLocaleString()} · {n.type}</p></div>{!n.read_at&&<button onClick={()=>void markRead(n.id)} className="shrink-0 text-xs font-bold text-violet-300">Read</button>}</div></article>)}{!notifications.length&&<p className="py-12 text-center text-slate-500">No notifications yet.</p>}</div></section>
    :kind==="library"?<section><div className="mb-5 flex flex-wrap items-center gap-2"><button onClick={()=>setLibraryTab("saved")} className={`rounded-full px-4 py-2 text-sm font-bold ${libraryTab==="saved"?"bg-white text-black":"border border-white/10 text-slate-300"}`}><Clock3 className="mr-2 inline size-4"/>Watch Later</button><button onClick={()=>setLibraryTab("liked")} className={`rounded-full px-4 py-2 text-sm font-bold ${libraryTab==="liked"?"bg-white text-black":"border border-white/10 text-slate-300"}`}><Heart className="mr-2 inline size-4"/>Liked</button><Link href="/playlists" className="rounded-full border border-white/10 px-4 py-2 text-sm font-bold text-slate-300">Playlists</Link><div className="relative ml-auto min-w-[220px]"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-500"/><Input value={libraryQuery} onChange={e=>setLibraryQuery(e.target.value)} placeholder="Search your library" className="rounded-full border-white/10 bg-white/[.04] pl-9 text-white"/></div></div>{filteredLibrary.length?<div className="grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filteredLibrary.map(v=><SupabaseVideoCard key={v.id} video={{id:String(v.id),title:v.title,thumbnailUrl:media(v.thumbnail_path),durationSeconds:v.duration_seconds,views:v.views,publishedAt:v.published_at,isShort:Array.isArray(v.tags)&&v.tags.includes("shorts")}}/>)}</div>:<Empty label={libraryTab==="saved"?"Your Watch Later list is empty.":"You have not liked any videos yet."}/>}</section>
    :kind==="history"?<section><div className="mb-5 flex items-center gap-3"><Clock3 className="size-5 text-violet-300"/><p className="text-sm text-slate-400">Recent watches are private to your account. Continue watching is surfaced on Home when progress is available.</p></div>{items.length?<div className="grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(v=><SupabaseVideoCard key={v.id} video={{id:String(v.id),title:v.title,thumbnailUrl:media(v.thumbnail_path),durationSeconds:v.duration_seconds,views:v.views,publishedAt:v.published_at,isShort:Array.isArray(v.tags)&&v.tags.includes("shorts")}}/>)}</div>:<Empty label="No watch history yet."/>}</section>
    :kind==="subscriptions"?<section><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(x=><Link key={x.channel_id} href={`/channel/${x.channels?.handle}`} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 transition hover:border-violet-300/30"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center overflow-hidden rounded-full bg-violet-500/20 font-bold text-white">{x.channels?.avatar_url?<img src={x.channels.avatar_url} className="size-full object-cover" alt=""/>:x.channels?.name?.slice(0,1)}</span><div><h3 className="font-bold text-white">{x.channels?.name}</h3><p className="text-xs text-slate-500">@{x.channels?.handle} · {Number(x.channels?.subscriber_count||0).toLocaleString()} subscribers</p></div></div></Link>)}</div>{!items.length&&<Empty label="You are not following any creators yet."/>}</section>
    :kind==="playlists"?<section><div className="mb-5 flex flex-wrap gap-2"><Input value={playlistTitle} onChange={e=>setPlaylistTitle(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void createPlaylist();}} placeholder="New playlist name" className="max-w-sm border-white/10 bg-white/[.04] text-white"/><Button onClick={()=>void createPlaylist()} disabled={!playlistTitle.trim()||creatingPlaylist}><Plus className="mr-2 size-4"/>Create playlist</Button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(p=><article key={p.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-start justify-between gap-3"><Link href={`/playlist/${p.id}`} className="min-w-0 flex-1"><h3 className="font-bold text-white">{p.title}</h3><p className="mt-1 text-sm text-slate-500">{p.description||"No description"}</p><p className="mt-3 text-xs text-slate-600">{p.visibility} · {Number(p.playlist_items?.[0]?.count||0)} items</p></Link><button onClick={()=>void deletePlaylist(p.id)} className="grid size-8 place-items-center rounded-full text-slate-500 hover:bg-rose-500/10 hover:text-rose-300" aria-label="Delete playlist"><Trash2 className="size-4"/></button></div></article>)}</div>{!items.length&&<Empty label="No playlists yet. Create your first private playlist above."/>}</section>
    :kind==="studio"?<CreatorStudio items={items}/>
    :kind==="posts"?<section className="space-y-4">{items.map(p=><article key={p.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="whitespace-pre-wrap text-white">{p.content}</p><p className="mt-3 text-xs text-slate-500">{Number(p.likes_count||0)} likes · {new Date(p.created_at).toLocaleString()}</p></article>)}{!items.length&&<Empty label="No community posts yet."/>}</section>
    :null}
  </main></HkTubeShell>;
}
function CreatorStudio({items}:{items:any[]}){const totalViews=items.reduce((a,v)=>a+Number(v.viewCount||0),0);const pending=items.filter(v=>v.moderationStatus!=="approved").length;return <section><div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<BarChart3 className="size-5"/>} value={totalViews.toLocaleString()} label="Total views"/><Stat icon={<Heart className="size-5"/>} value={items.reduce((a,v)=>a+Number(v.likes_count||0),0).toLocaleString()} label="Likes"/><Stat icon={<Clock3 className="size-5"/>} value={items.length.toLocaleString()} label="Uploads"/><Stat icon={<span className="text-sm font-black">!</span>} value={pending.toLocaleString()} label="Awaiting moderation"/></div><div className="mb-5 rounded-2xl border border-white/10 bg-white/[.025] p-4 text-sm text-slate-400">Creator Studio uses real uploaded records. Pending moderation content is not public discovery content. Open an item to inspect its watch page.</div>{items.length?<div className="grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(v=><SupabaseVideoCard key={v.id} video={{id:String(v.id),title:v.title,thumbnailUrl:v.thumbnailUrl,durationSeconds:v.durationSeconds,views:v.viewCount,publishedAt:v.publishedAt,isShort:v.category==="shorts"||v.tags?.includes("shorts")}}/>)}</div>:<Empty label="No uploads yet. Start from Create → Long Video or Clip."/>}</section>}
function Stat({icon,value,label}:{icon:any;value:string;label:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><span className="text-violet-300">{icon}</span><p className="mt-3 text-2xl font-black text-white">{value}</p><p className="text-xs text-slate-500">{label}</p></div>}
function Empty({label}:{label:string}){return <div className="rounded-3xl border border-dashed border-white/10 p-12 text-center text-slate-500">{label}</div>}
