import { ENV } from "./env";
export type AIWebSource={title:string;url:string;snippet:string};
export type AIMemory={memory_type:string;memory_key:string;value:unknown};
const clean=(v:string,max:number)=>v.replace(/\s+/g," ").trim().slice(0,max);
function token(req:{headers:Record<string,unknown>}){const v=req.headers.authorization;return typeof v==="string"&&v.startsWith("Bearer ")?v.slice(7):"";}
async function sb(path:string,t:string,method:"GET"|"POST"="GET",body?:unknown){
 if(!t)return null;
 return fetch(`${ENV.supabaseUrl}/rest/v1/${path}`,{method,headers:{apikey:ENV.supabaseAnonKey,Authorization:`Bearer ${t}`,"content-type":"application/json",...(method==="POST"?{Prefer:"resolution=merge-duplicates,return=minimal"}:{})},body:body?JSON.stringify(body):undefined});
}
export async function getAIUserId(req:{headers:Record<string,unknown>}){const t=token(req);if(!t)return null;try{const r=await fetch(`${ENV.supabaseUrl}/auth/v1/user`,{headers:{apikey:ENV.supabaseAnonKey,Authorization:`Bearer ${t}`}});if(!r.ok)return null;return ((await r.json()) as {id?:string}).id??null;}catch{return null;}}
export async function loadAIMemory(req:{headers:Record<string,unknown>}){const t=token(req);if(!t)return[] as AIMemory[];const r=await sb("ai_memory?select=memory_type,memory_key,value&enabled=eq.true&order=updated_at.desc&limit=30",t);if(!r?.ok)return[] as AIMemory[];const d=await r.json();return Array.isArray(d)?d as AIMemory[]:[];}
export async function saveAIMemories(req:{headers:Record<string,unknown>},ms:AIMemory[]){const t=token(req),u=await getAIUserId(req);if(!t||!u)return;const rows=ms.filter(m=>m.memory_type&&m.memory_key&&m.value!==undefined).slice(0,5).map(m=>({user_id:u,memory_type:clean(m.memory_type,40),memory_key:clean(m.memory_key,120),value:m.value,enabled:true}));if(rows.length)await sb("ai_memory?on_conflict=user_id,memory_type,memory_key",t,"POST",rows);}
export async function saveAIConversation(req:{headers:Record<string,unknown>},input:{title:string;module:string;messages:Array<{role:string;content:string}>}){const t=token(req),u=await getAIUserId(req);if(!t||!u)return;try{const r=await sb("ai_conversations",t,"POST",[{user_id:u,title:clean(input.title,160),module:clean(input.module,40),status:"active",context:{source:"hktube-ai"}}]);if(!r?.ok)return;const d=await r.json() as Array<{id?:string}>;const id=d[0]?.id;if(!id)return;await sb("ai_messages",t,"POST",input.messages.slice(-20).map(m=>({conversation_id:id,user_id:u,role:m.role,content:m.content.slice(0,12000),metadata:{}})));}catch{}}
export async function searchWeb(q:string):Promise<AIWebSource[]>{q=clean(q,300);if(!q)return[];try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{"user-agent":"HkTubeAI/1.0 (+https://hktube.vercel.app)"},signal:AbortSignal.timeout(7000)});if(!r.ok)return[];const h=await r.text(),out:AIWebSource[]=[];for(const b of (h.match(/<div class="result__body">[\\s\\S]*?<\\/div>\\s*<\\/div>/g)??[]).slice(0,6)){const a=b.match(/class="result__a"[^>]*href="([^"]+)"/),t=b.match(/class="result__a"[^>]*>([\\s\\S]*?)<\\/a>/),s=b.match(/class="result__snippet"[^>]*>([\\s\\S]*?)<\\/a?>/);if(!a||!t||!/^https?:\\/\\//i.test(a[1]))continue;const dec=(v:string)=>v.replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&quot;/g,'"');out.push({title:clean(dec(t[1]),180),url:a[1],snippet:clean(dec(s?.[1]??""),360)});}return out;}catch{return[];}}
export function shouldSearchWeb(ms:Array<{role:string;content:string}>){const q=ms.filter(m=>m.role==="user").at(-1)?.content.toLowerCase()??"";return !!q&&(/(latest|today|current|recent|news|price|weather|score|schedule|2026|right now|aaj|abhi|taaza|rate|khabar)/i.test(q)||q.length>=80||/\\b(who|what|when|where|why|how|compare|research|source|official|update|review)\\b/i.test(q));}
