import { z } from "zod";
import { randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { COOKIE_NAME, ONE_YEAR_MS } from "@shared/const";
import { sdk } from "./_core/sdk";
import { TRPCError } from "@trpc/server";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { addVideoToPlaylist, createChannel, createComment, createLocalAccount, createPlaylist, createPost, createReport, createVideo, getChannelById, getCreatorStudioDashboard, getLocalAccount, getRelatedVideos, getVideoById, getVideoEngagement, incrementVideoView, listAdminVideos, listChannelSubscriptions, listChannelsByOwner, listComments, listLiveStreams, listNotifications, listPlaylists, listPosts, listSavedVideos, listVideos, listWatchHistory, markNotificationRead, recordWatchHistory, removeVideo, toggleChannelSubscription, togglePostLike, toggleSavedVideo, toggleVideoLike } from "./db";
const videoCategory = z.enum(["regular", "shorts"]);
const mediaUrl = z.string().trim().refine(value => { if (value.startsWith("/manus-storage/")) return true; try { return Boolean(new URL(value)); } catch { return false; } }, "Provide a valid external URL or stored media path.");
export const videoInputSchema = z.object({ title: z.string().trim().min(1).max(255), description: z.string().trim().max(5000).optional().default(""), videoUrl: mediaUrl, videoStorageKey: z.string().trim().max(512).optional(), thumbnailUrl: mediaUrl.optional(), thumbnailStorageKey: z.string().trim().max(512).optional(), captionUrl: mediaUrl.optional(), captionStorageKey: z.string().trim().max(512).optional(), durationSeconds: z.number().int().min(0).max(86400).default(0), category: videoCategory.default("regular"), channelId: z.number().int().positive().optional() });
const channelInputSchema = z.object({ handle: z.string().trim().regex(/^[A-Za-z0-9_]{3,64}$/, "Use 3-64 letters, numbers, or underscores."), displayName: z.string().trim().min(1).max(255), description: z.string().trim().max(5000).optional().default("") });
const commentInput = z.object({ body: z.string().trim().min(1).max(2000), videoId: z.number().int().positive().optional(), postId: z.number().int().positive().optional(), parentId: z.number().int().positive().optional() }).refine(value => Boolean(value.videoId || value.postId), "A video or post is required.");
export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    register: publicProcedure.input(z.object({ name: z.string().trim().min(2).max(120), email: z.string().trim().toLowerCase().email().max(320), password: z.string().min(8).max(128) })).mutation(async ({ ctx, input }) => { const identifier = input.email.toLowerCase(); if (await getLocalAccount(identifier)) throw new TRPCError({ code: "CONFLICT", message: "An HkTube account already exists for this email." }); const salt = randomBytes(16).toString("hex"); const passwordHash = `${salt}:${scryptSync(input.password, salt, 64).toString("hex")}`; const user = await createLocalAccount({ openId: `local_${randomBytes(18).toString("hex")}`, name: input.name, email: identifier, identifier, passwordHash }); const token = await sdk.signSession({ openId: user.openId, appId: process.env.VITE_APP_ID || "hktube", name: user.name || input.name }); const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.cookie(COOKIE_NAME, token, { ...cookieOptions, maxAge: ONE_YEAR_MS }); return user; }),
    login: publicProcedure.input(z.object({ email: z.string().trim().toLowerCase().email().max(320), password: z.string().min(1).max(128) })).mutation(async ({ ctx, input }) => { const record = await getLocalAccount(input.email.toLowerCase()); if (!record) throw new TRPCError({ code: "UNAUTHORIZED", message: "Email or password is incorrect." }); const [salt, stored] = record.account.passwordHash.split(":"); if (!salt || !stored) throw new TRPCError({ code: "UNAUTHORIZED", message: "Email or password is incorrect." }); const candidate = scryptSync(input.password, salt, 64); if (!timingSafeEqual(candidate, Buffer.from(stored, "hex"))) throw new TRPCError({ code: "UNAUTHORIZED", message: "Email or password is incorrect." }); const token = await sdk.signSession({ openId: record.user.openId, appId: process.env.VITE_APP_ID || "hktube", name: record.user.name || "HkTube member" }); const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.cookie(COOKIE_NAME, token, { ...cookieOptions, maxAge: ONE_YEAR_MS }); return record.user; }),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; })
  }),
  videos: router({
    latest: publicProcedure.input(z.object({ limit: z.number().int().min(1).max(60).optional() }).optional()).query(({ input }) => listVideos({ mode: "latest", limit: input?.limit })),
    shorts: publicProcedure.input(z.object({ limit: z.number().int().min(1).max(60).optional() }).optional()).query(({ input }) => listVideos({ category: "shorts", mode: "latest", limit: input?.limit })),
    trending: publicProcedure.input(z.object({ limit: z.number().int().min(1).max(60).optional() }).optional()).query(({ input }) => listVideos({ mode: "trending", limit: input?.limit })),
    search: publicProcedure.input(z.object({ query: z.string().trim().max(120), limit: z.number().int().min(1).max(60).optional() })).query(({ input }) => input.query ? listVideos({ search: input.query, mode: "latest", limit: input.limit }) : []),
    byId: publicProcedure.input(z.object({ id: z.number().int().positive() })).query(({ input }) => getVideoById(input.id)), related: publicProcedure.input(z.object({ id: z.number().int().positive(), category: videoCategory })).query(({ input }) => getRelatedVideos(input.id, input.category)), recordView: publicProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => incrementVideoView(input.id)), engagement: publicProcedure.input(z.object({ id: z.number().int().positive() })).query(({ ctx, input }) => getVideoEngagement(input.id, ctx.user?.id)), toggleLike: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => toggleVideoLike(input.id, ctx.user.id)),
    create: adminProcedure.input(videoInputSchema).mutation(async ({ ctx, input }) => { if (input.channelId) { const channel = await getChannelById(input.channelId); if (!channel || channel.ownerId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN", message: "You can only upload to your own channel." }); } return createVideo({ ...input, description: input.description || null, thumbnailUrl: input.thumbnailUrl ?? null, thumbnailStorageKey: input.thumbnailStorageKey ?? null, captionUrl: input.captionUrl ?? null, captionStorageKey: input.captionStorageKey ?? null, videoStorageKey: input.videoStorageKey ?? null, channelId: input.channelId ?? null, uploadedById: ctx.user.id }); }), adminList: adminProcedure.query(() => listAdminVideos()), remove: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => removeVideo(input.id)),
  }),
  comments: router({ list: publicProcedure.input(z.object({ videoId: z.number().int().positive().optional(), postId: z.number().int().positive().optional() })).query(({ input }) => listComments(input)), create: protectedProcedure.input(commentInput).mutation(({ ctx, input }) => createComment({ ...input, authorId: ctx.user.id })) }),
  subscriptions: router({ mine: protectedProcedure.query(({ ctx }) => listChannelSubscriptions(ctx.user.id)), toggle: protectedProcedure.input(z.object({ channelId: z.number().int().positive() })).mutation(({ ctx, input }) => toggleChannelSubscription(input.channelId, ctx.user.id)) }),
  channels: router({ mine: protectedProcedure.query(({ ctx }) => listChannelsByOwner(ctx.user.id)), create: protectedProcedure.input(channelInputSchema).mutation(({ ctx, input }) => createChannel({ ownerId: ctx.user.id, handle: input.handle, displayName: input.displayName, description: input.description || null })) }),
  live: router({ latest: publicProcedure.input(z.object({ limit: z.number().int().min(1).max(60).optional() }).optional()).query(({ input }) => listLiveStreams(input?.limit)) }),
  playlists: router({ mine: protectedProcedure.query(({ ctx }) => listPlaylists(ctx.user.id)), create: protectedProcedure.input(z.object({ title: z.string().trim().min(1).max(255), description: z.string().trim().max(5000).optional(), visibility: z.enum(["public", "unlisted", "private"]).optional() })).mutation(({ ctx, input }) => createPlaylist({ ...input, ownerId: ctx.user.id })), add: protectedProcedure.input(z.object({ playlistId: z.number().int().positive(), videoId: z.number().int().positive() })).mutation(({ ctx, input }) => addVideoToPlaylist({ ...input, ownerId: ctx.user.id })) }),
  watch_history: router({ mine: protectedProcedure.query(({ ctx }) => listWatchHistory(ctx.user.id)), record: protectedProcedure.input(z.object({ videoId: z.number().int().positive(), watchedSeconds: z.number().int().min(0).max(86400).optional() })).mutation(({ ctx, input }) => recordWatchHistory({ ...input, userId: ctx.user.id })) }),
  notifications: router({ mine: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)), markRead: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => markNotificationRead(input.id, ctx.user.id)) }),
  posts: router({ latest: publicProcedure.input(z.object({ limit: z.number().int().min(1).max(100).optional() }).optional()).query(({ input }) => listPosts(input?.limit)), create: protectedProcedure.input(z.object({ body: z.string().trim().min(1).max(5000), channelId: z.number().int().positive().optional(), mediaUrl: mediaUrl.optional(), linkUrl: mediaUrl.optional() })).mutation(({ ctx, input }) => createPost({ ...input, authorId: ctx.user.id })), toggleLike: protectedProcedure.input(z.object({ postId: z.number().int().positive() })).mutation(({ ctx, input }) => togglePostLike(input.postId, ctx.user.id)) }),
  reports: router({ create: protectedProcedure.input(z.object({ reason: z.string().trim().min(1).max(120), details: z.string().trim().max(2000).optional(), videoId: z.number().int().positive().optional(), postId: z.number().int().positive().optional(), commentId: z.number().int().positive().optional() }).refine(value => Boolean(value.videoId || value.postId || value.commentId), "A report target is required.")).mutation(({ ctx, input }) => createReport({ ...input, reporterId: ctx.user.id })) }),
  library: router({ saved: protectedProcedure.query(({ ctx }) => listSavedVideos(ctx.user.id)), toggleSaved: protectedProcedure.input(z.object({ videoId: z.number().int().positive() })).mutation(({ ctx, input }) => toggleSavedVideo(input.videoId, ctx.user.id)) }),
  creator_studio: router({ dashboard: protectedProcedure.query(({ ctx }) => getCreatorStudioDashboard(ctx.user.id)) }),
});
export type AppRouter = typeof appRouter;
