import { useEffect, useState } from 'react'
import { Activity, Bot, CircleDollarSign, FileWarning, LockKeyhole, Radio, Search, ShieldCheck, Users, Wrench } from 'lucide-react'
import { setEmergencyLock, verifyOwnerAccess, type AdminSecurityState } from '../lib/adminSecurity'
import AICommandSystem from '../components/admin/AICommandSystem'
import AuditLogs from '../components/admin/AuditLogs'

type Section = { id: string; label: string; icon: typeof Activity }
const sections: Section[] = [{ id: 'overview', label: 'Server / Build Health', icon: Activity }, { id: 'auto-fix', label: 'Auto Fix / Errors', icon: Wrench }, { id: 'adsense', label: 'AdSense / Compliance', icon: Search }, { id: 'payments', label: 'Payments / PayFast', icon: CircleDollarSign }, { id: 'seo', label: 'SEO / GEO', icon: Search }, { id: 'support', label: 'Support', icon: Users }, { id: 'security', label: 'Security / Privacy', icon: LockKeyhole }, { id: 'monetization', label: 'Monetization', icon: CircleDollarSign }, { id: 'users', label: 'Users / Creators', icon: Users }, { id: 'live', label: 'Live', icon: Radio }, { id: 'ai', label: 'AI Control', icon: Bot }, { id: 'approval', label: 'Approval Queue', icon: FileWarning }]
export default function AdminControlCenter({ userId }: { userId: string }) { const [security, setSecurity] = useState<AdminSecurityState | null>(null); const [active, setActive] = useState('overview'); const [message, setMessage] = useState(''); useEffect(() => { verifyOwnerAccess().then(setSecurity) }, []); if (!security) return <div className="studio-loading"><div className="spinner" /></div>; if (!security.authorized) return <div className="empty-state"><ShieldCheck size={40} /><h3>Admin access denied</h3><p>{security.reason}</p></div>; const toggleLock = async () => { const next = !security.emergencyLocked; const { error } = await setEmergencyLock('admin_execution', next, next ? 'Owner emergency pause' : 'Owner resumed sensitive actions'); if (error) setMessage(error.message); else { setSecurity({ ...security, emergencyLocked: next }); setMessage(next ? 'Sensitive execution is paused.' : 'Sensitive execution is available after normal approval checks.') } }; return <div className="admin-control-center"><header className="studio-header"><div><span className="eyebrow"><ShieldCheck size={14} /> Private owner area</span><h1>HkTube Admin Control Center</h1><p className="muted">Server authorization is required; this page is not a security boundary by itself.</p></div><button className={`btn-secondary ${security.emergencyLocked ? 'btn-danger' : ''}`} onClick={toggleLock}><LockKeyhole size={16} /> {security.emergencyLocked ? 'Resume sensitive actions' : 'Emergency lock'}</button></header>{message && <div className="form-success">{message}</div>}<div className="admin-layout"><nav className="studio-nav">{sections.map(section => { const Icon = section.icon; return <button className={`studio-nav-item ${active === section.id ? 'active' : ''}`} key={section.id} onClick={() => setActive(section.id)}><Icon size={16} /> <span>{section.label}</span></button> })}</nav><main className="studio-content">{active === 'ai' ? <AICommandSystem actorId={userId} /> : active === 'security' ? <AuditLogs /> : <section className="studio-card"><span className="eyebrow"><Activity size={14} /> {sections.find(item => item.id === active)?.label}</span><h2>Operational workspace</h2><p className="muted">This section is ready for server-side provider data and keeps changes behind the protected admin workflow. Safe diagnostics may be automated; sensitive changes require owner approval.</p><div className="admin-health-grid"><div><strong>Auth</strong><span>Protected</span></div><div><strong>RLS</strong><span>Enabled in migration</span></div><div><strong>Payment mode</strong><span>{import.meta.env.VITE_PAYFAST_MODE || 'Server-configured'}</span></div></div></section>}</main></div></div> }
