import { Link } from 'react-router-dom'

export type LegalKind = 'privacy' | 'terms' | 'refund-policy' | 'disclaimer' | 'contact' | 'copyright'
const copy: Record<LegalKind, { title: string; paragraphs: string[] }> = {
  privacy: { title: 'Privacy Policy', paragraphs: ['HkTube collects only the account, content, and usage information needed to operate the service, secure accounts, improve performance, and respond to support requests.', 'You control the content you publish and may request correction or deletion of account information where applicable. HkTube does not publish private owner information.'] },
  terms: { title: 'Terms of Service', paragraphs: ['By using HkTube, you agree to publish only content you are entitled to share and to follow applicable law. You are responsible for your account credentials and activity.', 'HkTube may restrict content or accounts that violate these terms, safety rules, or copyright requirements.'] },
  'refund-policy': { title: 'Refund Policy', paragraphs: ['Any paid HkTube feature will clearly disclose its price and cancellation terms before purchase. Where a refund is available, requests are reviewed against the applicable purchase terms and legal requirements.', 'Contact HkTube through the support route below with your order details; never include passwords or secret keys.'] },
  disclaimer: { title: 'Disclaimer', paragraphs: ['HkTube is a user-generated content platform. Content is provided by its creators and may not represent HkTube views or advice.', 'Availability, features, and playback quality can vary by device, network, provider limits, and creator permissions.'] },
  contact: { title: 'Contact HkTube', paragraphs: ['For account, safety, copyright, or product questions, use the in-app contact form or the support email configured by the HkTube operator. Do not submit passwords, access tokens, or service-role credentials.', 'Copyright notices should include the work, the relevant HkTube URL, your contact details, and a statement of good-faith belief.'] },
  copyright: { title: 'Copyright', paragraphs: ['HkTube respects intellectual property rights. If you believe content infringes your copyright, send a complete notice through the contact route so it can be reviewed.', 'Creators must upload only content they own or are authorized to distribute and should respond promptly to legitimate rights-holder requests.'] },
}
export default function LegalPages({ kind }: { kind: LegalKind }) { const page = copy[kind]; return <main className="legal-page"><div className="legal-page-inner"><Link className="hk-brand" to="/"><span className="logo-hk">Hk</span><span className="logo-tube">Tube</span></Link><h1>{page.title}</h1>{page.paragraphs.map(text => <p key={text}>{text}</p>)}<p className="legal-updated">Last updated: August 2026</p><Link to="/">Return to HkTube</Link></div></main> }
