import { useEffect, useState } from 'react'
import { Bot, History, Send, ShieldCheck, Sparkles } from 'lucide-react'
import { createConversation, saveMessage, understand } from '../../lib/ai/kalibro-brain'

type Props = { userId: string }
export default function AIChatInterface({ userId }: Props) {
  const [input, setInput] = useState(''); const [messages, setMessages] = useState<{role:'user'|'assistant'; content:string}[]>([]); const [busy, setBusy] = useState(false); const [status, setStatus] = useState('Ready')
  useEffect(() => { setMessages([{ role: 'assistant', content: 'I’m HkTube AI. Ask about your creator workflow, video metadata, code, SEO, or a safe troubleshooting plan.' }]) }, [])
  const send = async () => { if (!input.trim() || busy) return; const request=input.trim(); setInput(''); setBusy(true); setStatus('Analyzing request…'); setMessages(prev => [...prev, { role:'user', content:request }]); const conversation = await createConversation(userId, request.slice(0, 48)).catch(() => ({ data: null })); const result=await understand({ userId, request, conversationId: conversation.data?.id }); const content=result.ok ? `${result.summary}\n\n${result.plan.map((step,index)=>`${index+1}. ${step}`).join('\n')}${result.suggestions.length ? `\n\nSuggestions: ${result.suggestions.join(' ')}` : ''}` : result.summary; setMessages(prev => [...prev, { role:'assistant', content }]); if (conversation.data?.id) await saveMessage(userId, conversation.data.id, 'assistant', content); setStatus(result.requiresApproval ? 'Approval required' : 'Complete'); setBusy(false) }
  return <section className="studio-card ai-surface"><div className="ai-heading"><div><span className="eyebrow"><Sparkles size={14}/> HkTube AI</span><h2>KaliBro Chat</h2><p className="muted">Natural-language assistance with permission-aware execution.</p></div><span className="ai-status"><ShieldCheck size={14}/> {status}</span></div><div className="ai-chat-log">{messages.map((message,index)=><div key={index} className={`ai-message ${message.role}`}><Bot size={16}/><div><strong>{message.role === 'user' ? 'You' : 'HkTube AI'}</strong><p>{message.content}</p></div></div>)}</div><div className="ai-input-row"><input value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==='Enter') void send()}} placeholder="Ask KaliBro to help with your creator workflow…" aria-label="AI request"/><button className="btn-primary" onClick={()=>void send()} disabled={busy || !input.trim()}><Send size={16}/> {busy?'Working…':'Send'}</button></div><div className="ai-trust-note"><History size={14}/> Conversations and tasks are scoped to your account. Credentials and payment secrets are never stored in memory.</div></section>
}
