import { supabase } from '../supabase'
export type PermissionLevel = 'read' | 'suggest' | 'execute' | 'admin'
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical'
export const DANGEROUS_ACTIONS = ['delete data', 'change permissions', 'change payment', 'disable security', 'delete users', 'major deployment', 'change monetization', 'change legal']
const blocked = [/credential\s*theft/i, /steal\s+(?:a|the)\s+password/i, /malware|ransomware|keylogger/i, /bypass\s+(?:security|platform|authentication)/i, /exploit\s+\w+/i, /sexual\s+content\s+involving\s+minors/i]
export function validateAIInput(input: string) { const value = input.trim(); if (!value || value.length > 12000) return { safe: false, reason: 'Please provide a non-empty request under 12,000 characters.' }; const match = blocked.find(pattern => pattern.test(value)); return match ? { safe: false, reason: 'I cannot help with harmful, illegal, exploitative, credential-stealing, or security-bypass requests. I can help with defensive, lawful alternatives.' } : { safe: true as const, value } }
export function detectPromptInjection(input: string) { return /(ignore\s+(all|previous)|reveal\s+(the\s+)?system prompt|developer message|disable\s+safety|act\s+as\s+owner)/i.test(input) }
export function assessRisk(action = ''): { level: RiskLevel; requiresApproval: boolean } { const dangerous = DANGEROUS_ACTIONS.some(item => action.toLowerCase().includes(item)); return dangerous ? { level: 'critical', requiresApproval: true } : { level: action ? 'low' : 'medium', requiresApproval: false } }
export async function hasPermission(userId: string, required: PermissionLevel, resource = '*') { if (!userId) return false; if (required === 'read') return true; try { const { data } = await supabase.from('ai_permissions').select('permission,expires_at').eq('user_id', userId).in('permission', ['admin', required, required === 'execute' ? 'suggest' : required]).or(`resource.eq.${resource},resource.eq.*`); const rank: Record<PermissionLevel, number> = { read: 1, suggest: 2, execute: 3, admin: 4 }; return (data ?? []).some(row => rank[row.permission as PermissionLevel] >= rank[required] && (!row.expires_at || new Date(row.expires_at).getTime() > Date.now())) } catch { return false } }
export async function audit(userId: string, event: string, metadata: Record<string, unknown> = {}) { try { await supabase.from('ai_usage_logs').insert({ user_id: userId || null, provider: 'kalibro-brain', capability: 'text', operation: event, status: 'audit', metadata }) } catch { /* audit failures never break user workflows */ } }
