import { useEffect, useRef, useState, type ReactNode } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { supabase } from "@/lib/supabase";
import { recordDiscoveryEvent, setRecommendationFeedback } from "@/lib/supabaseDiscovery";
import { recordVideoView, toggleChannelSubscription, toggleVideoLike, toggleVideoSave } from "@/lib/supabaseEngagement";
import {
  Bookmark, Check, ChevronDown, CircleHelp, Flag, Gauge, Heart, Link2,
  MessageCircle, MoreVertical, Play, RefreshCw, Share2, Sparkles,
  UserRound, Volume2, VolumeX, X, Zap
} from "lucide-react";

type ClipItem={id:string;title:string;description:string|null;video_path:string|null;thumbnail_path:string|null;views:number;likes_count:number;channel_id:string|null;tags:string[]|null};
type Channel={id:string;handle:string;name:string;avatar_url:string|null;subscriber_count:number};
type Panel="none"|"more"|"share"|"speed"|"help";
const media=(bucket:string,path:string|null)=>path?( /^https?:\\/\\//i.test(path)?path:supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl):null;
const count=(n:number)=>n>=1_000_000?(`${(n/1_000_000).toFixed(1)}M`):n>=1_000?(`${(n/1_000).toFixed(n>=10_000?0:1)}K`):String(Math.max(0,Math.round(n)));
const time=(n:number)=>{if(!Number.isFinite(n)||n<0)return "0:00";const s=Math.floor(n);return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`;};

export function ClipsView({items,mode,onModeChange}:{items:ClipItem[];mode:"for-you"|"following";onModeChange:(m:"for-you"|"following")=>void}){
 const {user}=useAuth();
 const [muted,setMuted]=useState(true),[autoplay,setAutoplay]=useState(true),[dataSaver,setDataSaver]=useState(false);
 const [paused,setPaused]=useState<Record<string,boolean>>({}),[liked,setLiked]=useState<Record<string,boolean>>({}),[saved,setSaved]=useState<Record<string,boolean>>({});
 const [likes,setLikes]=useState<Record<string,number>>(()=>Object.fromEntries(items.map(x=>[x.id,Number(x.likes_count||0)])));
 const [channels,setChannels]=useState<Record<string,Channel>>({}),[following,setFollowing]=useState<Record<string,boolean>>({});
 const [ready,setReady]=useState<Record<string,boolean>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[progress,setProgress]=useState<Record<string,number>>({});
 const [duration,setDuration]=useState<Record<string,number>>({}),[activeId,setActiveId]=useState(items[0]?.id??null);
 const [panel,setPanel]=useState<Panel>("none"),[shareItem,setShareItem]=useState<ClipItem|null>(null),[speed,setSpeed]=useState(1),[clear,setClear]=useState(false);
 const [burst,setBurst]=useState<Record<string,boolean>>({});
 const refs=useRef<Record<string,HTMLVideoElement|null>>({}),seen=useRef(new Set<string>()),lastTap=useRef({id:"",time:0}),press=useRef<number|null>(null);
 const buckets=useRef<Record<string,Set<string>>>({}),history=useRef<Record<string,number>>({});

 useEffect(()=>{setAutoplay(localStorage.getItem("hktube-autoplay")!=="disabled");setDataSaver(localStorage.getItem("hktube-data-saver")==="enabled")},[]);
 useEffect(()=>{const ids=[...new Set(items.map(x=>x.channel_id).filter(Boolean))] as string[];if(!ids.length)return;let dead=false;void supabase.from("channels").select("id,handle,name,avatar_url,subscriber_count").in("id",ids).then(({data})=>{if(!dead)setChannels(Object.fromEntries((data??[]).map(x=>[String(x.id),x as Channel])))});return()=>{dead=true}},[items]);
 useEffect(()=>{if(!user)return;const ids=[...new Set(items.map(x=>x.channel_id).filter(Boolean))] as string[];if(!ids.length)return;let dead=false;void supabase.from("subscriptions").select("channel_id").eq("subscriber_id",user.id).in("channel_id",ids).then(({data})=>{if(!dead)setFollowing(Object.fromEntries((data??[]).map(x=>[String(x.channel_id),true])))});return()=>{dead=true}},[items,user?.id]);
 useEffect(()=>{setLikes(Object.fromEntries(items.map(x=>[x.id,Number(x.likes_count||0)])));setPaused({});setReady({});setErrors({});setProgress({});setDuration({});setActiveId(items[0]?.id??null);refs.current={};seen.current.clear();buckets.current={};history.current={}},[items]);

 const play=(id:string,shouldPlay=true)=>{const v=refs.current[id];if(!v)return;v.muted=muted;v.playbackRate=speed;if(shouldPlay&&autoplay)void v.play().then(()=>setPaused(s=>({...s,[id]:false}))).catch(()=>setPaused(s=>({...s,[id]:true})));else{v.pause();setPaused(s=>({...s,[id]:true}))}};
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{const id=(e.target as HTMLElement).dataset.clipId;if(!id)return;const v=refs.current[id];if(!v)return;if(e.isIntersecting&&e.intersectionRatio>.68){setActiveId(id);play(id,true);if(!seen.current.has(id)){seen.current.add(id);void recordVideoView(id).catch(()=>undefined);void recordDiscoveryEvent({eventType:"play_start",objectType:"short",objectId:id}).catch(()=>undefined)}}else v.pause()}),{threshold:[.2,.68,.9]});const t=window.setTimeout(()=>document.querySelectorAll<HTMLElement>("[data-clip-id]").forEach(x=>observer.observe(x)),50);return()=>{clearTimeout(t);observer.disconnect()}},[items,autoplay,muted,speed]);

 async function like(id:string,showBurst=false){if(!user)return startLogin();try{const r=await toggleVideoLike(id);setLiked(s=>({...s,[id]:r.liked}));setLikes(s=>({...s,[id]:Number(r.count)}));if(showBurst&&r.liked){setBurst(s=>({...s,[id]:true}));setTimeout(()=>setBurst(s=>({...s,[id]:false})),650)}void recordDiscoveryEvent({eventType:r.liked?"like":"unlike",objectType:"short",objectId:id}).catch(()=>undefined)}catch(e){toast.error(e instanceof Error?e.message:"Unable to update like.")}}
 async function save(id:string){if(!user)return startLogin();try{const r=await toggleVideoSave(id);setSaved(s=>({...s,[id]:r}));void recordDiscoveryEvent({eventType:r?"save":"unsave",objectType:"short",objectId:id}).catch(()=>undefined);toast.success(r?"Saved to Library":"Removed from Library")}catch(e){toast.error(e instanceof Error?e.message:"Unable to save Clip.")}}
 async function follow(id:string){if(!user)return startLogin();try{const r=await toggleChannelSubscription(id);setFollowing(s=>({...s,[id]:r.subscribed}));setChannels(s=>({...s,[id]:s[id]?{...s[id],subscriber_count:Number(r.count)}:s[id]}));void recordDiscoveryEvent({eventType:r.subscribed?"follow":"unfollow",objectType:"channel",objectId:id}).catch(()=>undefined)}catch(e){toast.error(e instanceof Error?e.message:"Unable to update following.")}}
 async function tune(item:ClipItem,type:"not_interested"|"hide_creator"|"hide_topic"){if(!user)return startLogin();try{const topic=type==="hide_topic"?(item.tags?.find(x=>x.toLowerCase()!=="shorts")??null):null;await setRecommendationFeedback(item.id,type,topic);setPanel("none");toast.success(type==="not_interested"?"Fewer Clips like this.":type==="hide_creator"?"Fewer Clips from this creator.":"Fewer Clips on this topic.")}catch(e){toast.error(e instanceof Error?e.message:"Unable to tune recommendations.")}}
 async function share(item:ClipItem){const url=`${location.origin}/watch/${item.id}`;try{if(navigator.share)await navigator.share({title:item.title,url});else{await navigator.clipboard.writeText(url);toast.success("Clip link copied")}void recordDiscoveryEvent({eventType:"share",objectType:"short",objectId:item.id}).catch(()=>undefined)}catch{}finally{setPanel("none");setShareItem(null)}}
 async function copy(item:ClipItem){try{await navigator.clipboard.writeText(`${location.origin}/watch/${item.id}`);toast.success("Clip link copied");void recordDiscoveryEvent({eventType:"share",objectType:"short",objectId:item.id,context:{method:"copy_link"}}).catch(()=>undefined)}catch{toast.error("Could not copy the link.")}}

 function surface(id:string){const now=Date.now();if(lastTap.current.id===id&&now-lastTap.current.time<300){void like(id,true);lastTap.current={id:"",time:0};return}lastTap.current={id,time:now};setTimeout(()=>{if(lastTap.current.id===id&&Date.now()-lastTap.current.time>=290){const v=refs.current[id];if(v?.paused)play(id,true);else{v?.pause();setPaused(s=>({...s,[id]:true}))}}},310)}
 function down(id:string){if(press.current)clearTimeout(press.current);press.current=window.setTimeout(()=>{const v=refs.current[id];if(v){v.playbackRate=2;toast("2× playback")}},380)}
 function up(id:string){if(press.current)clearTimeout(press.current);const v=refs.current[id];if(v)v.playbackRate=speed}

 if(!items.length)return null;
 return <div className="fixed inset-0 z-[80] overflow-hidden bg-black text-white">
  {!clear&&<header className="pointer-events-none absolute inset-x-0 top-0 z-50 flex items-start justify-between px-3 pt-[max(12px,env(safe-area-inset-top))] sm:px-5">
   <Link href="/" className="pointer-events-auto grid size-10 place-items-center rounded-full border border-white/10 bg-black/45 backdrop-blur-xl" aria-label="Close Clips"><X className="size-5"/></Link>
   <div className="pointer-events-auto rounded-full border border-white/10 bg-black/45 p-1 text-xs font-black backdrop-blur-xl"><button onClick={()=>onModeChange("for-you")} className={`rounded-full px-4 py-2 ${mode==="for-you"?"bg-white text-black":"text-white/70"}`}>For You</button><button onClick={()=>onModeChange("following")} className={`rounded-full px-4 py-2 ${mode==="following"?"bg-white text-black":"text-white/70"}`}>Following</button></div>
   <button onClick={()=>setPanel("more")} className="pointer-events-auto grid size-10 place-items-center rounded-full border border-white/10 bg-black/45 backdrop-blur-xl" aria-label="Clips options"><MoreVertical className="size-5"/></button>
  </header>}
  {clear&&<button onClick={()=>setClear(false)} className="absolute right-3 top-[max(12px,env(safe-area-inset-top))] z-[120] rounded-full border border-white/10 bg-black/60 px-3 py-2 text-xs font-black backdrop-blur-xl">Show controls</button>}
  <div className="h-full snap-y snap-mandatory overflow-y-auto overscroll-y-contain [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
   {items.map((item,index)=>{const video=media("videos",item.video_path),thumb=media("thumbnails",item.thumbnail_path),channel=item.channel_id?channels[item.channel_id]:undefined,failed=errors[item.id],active=activeId===item.id;return <section key={item.id} data-clip-id={item.id} className="relative flex h-[100dvh] snap-start items-center justify-center overflow-hidden bg-black">
    {thumb&&<img src={thumb} alt="" aria-hidden className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-500 ${ready[item.id]?"opacity-0":"opacity-100"}`}/>}
    {video&&<video ref={el=>{refs.current[item.id]=el}} src={video} playsInline muted defaultMuted loop autoPlay={autoplay&&index===0} preload={dataSaver?(index<1?"auto":"metadata"):(index<2?"auto":"metadata")} controls={false} disablePictureInPicture className="absolute inset-0 z-10 h-full w-full object-cover" onLoadedMetadata={e=>{const v=e.currentTarget;setDuration(s=>({...s,[item.id]:Number.isFinite(v.duration)?v.duration:0}));if(v.videoWidth>0&&v.videoHeight>0){setReady(s=>({...s,[item.id]:true}));setErrors(s=>{const n={...s};delete n[item.id];return n});v.muted=muted;v.playbackRate=speed;if(active&&autoplay)void v.play().catch(()=>undefined)}else setErrors(s=>({...s,[item.id]:"The video stream has no decodable video track."}))}} onCanPlay={e=>{const v=e.currentTarget;if(v.videoWidth>0&&v.videoHeight>0)setReady(s=>({...s,[item.id]:true}));if(active&&autoplay)void v.play().catch(()=>undefined)}} onTimeUpdate={e=>{const v=e.currentTarget,p=v.duration>0?v.currentTime/v.duration:0;setProgress(s=>({...s,[item.id]:p}));if(user&&Math.floor(v.currentTime)-(history.current[item.id]??0)>=5){history.current[item.id]=Math.floor(v.currentTime);void supabase.from("watch_history").upsert({user_id:user.id,video_id:item.id,progress_seconds:Math.floor(v.currentTime),watched_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"user_id,video_id"}).then(()=>undefined,()=>undefined)}const bucket=p>=.9?"watch_90_percent":p>=.75?"watch_75_percent":p>=.5?"watch_50_percent":p>=.25?"watch_25_percent":p>=.1?"watch_10_percent":null;if(bucket){const set=buckets.current[item.id]??new Set<string>();if(!set.has(bucket)){set.add(bucket);buckets.current[item.id]=set;void recordDiscoveryEvent({eventType:bucket,objectType:"short",objectId:item.id,watchSeconds:Math.floor(v.currentTime),positionSeconds:Math.floor(v.currentTime)}).catch(()=>undefined)}}}} onEnded={()=>void recordDiscoveryEvent({eventType:"complete",objectType:"short",objectId:item.id}).catch(()=>undefined)} onError={e=>{const code=e.currentTarget.error?.code;setErrors(s=>({...s,[item.id]:code?`Playback error ${code}.`:"Playback error."}));void recordDiscoveryEvent({eventType:"playback_error",objectType:"short",objectId:item.id,context:{media_error_code:code??null}}).catch(()=>undefined)}} onClick={()=>surface(item.id)} onPointerDown={()=>down(item.id)} onPointerUp={()=>up(item.id)} onPointerCancel={()=>up(item.id)}/>}
    <div className="pointer-events-none absolute inset-0 z-20 bg-gradient-to-b from-black/30 via-transparent to-black/85"/>
    {active&&<div className="pointer-events-none absolute inset-x-0 top-0 z-30 h-1 bg-white/15"><div className="h-full bg-white transition-[width] duration-100" style={{width:`${Math.min(100,(progress[item.id]??0)*100)}%`}}/></div>}
    {failed&&<div className="absolute left-1/2 top-1/2 z-40 w-[min(88vw,430px)] -translate-x-1/2 -translate-y-1/2 rounded-3xl border border-white/10 bg-black/90 p-5 text-center backdrop-blur-xl"><p className="font-black">This Clip cannot be played</p><p className="mt-2 text-xs text-white/60">{failed}</p><Link href={`/watch/${item.id}`} className="mt-4 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-black text-black"><Play className="size-4 fill-current"/>Open video</Link></div>}
    {!ready[item.id]&&!failed&&video&&!clear&&<div className="pointer-events-none absolute left-1/2 top-1/2 z-30 -translate-x-1/2 -translate-y-1/2 rounded-full bg-black/45 px-3 py-2 text-xs font-bold text-white/75 backdrop-blur-xl">Loading Clip…</div>}
    {burst[item.id]&&<div className="pointer-events-none absolute left-1/2 top-1/2 z-40 -translate-x-1/2 -translate-y-1/2 animate-[ping_.65s_ease-out]"><Heart className="size-28 fill-current"/></div>}
    {!clear&&<><div className="absolute bottom-[max(20px,env(safe-area-inset-bottom))] left-3 right-20 z-30 max-w-[650px] sm:left-1/2 sm:right-auto sm:w-[620px] sm:-translate-x-1/2 sm:pr-16">
      <div className="flex items-center gap-2"><Link href={channel?`/channel/${channel.handle}`:`/watch/${item.id}`} className="pointer-events-auto flex min-w-0 items-center gap-2"><span className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-full border border-white/30 bg-white/10">{channel?.avatar_url?<img src={channel.avatar_url} alt="" className="size-full object-cover"/>:<UserRound className="size-4"/>}</span><span className="truncate text-sm font-black">@{channel?.handle??"hktube"}</span></Link>{channel&&<button onClick={()=>void follow(channel.id)} className={`pointer-events-auto rounded-full px-3 py-1.5 text-[11px] font-black ${following[channel.id]?"bg-white/15":"bg-white text-black"}`}>{following[channel.id]?"Following":"Follow"}</button>}</div>
      <h2 className="mt-2 line-clamp-2 text-base font-black leading-6 sm:text-lg">{item.title}</h2>{item.description&&<p className="mt-1 line-clamp-2 text-sm text-white/75">{item.description}</p>}
      {!!item.tags?.length&&<div className="mt-2 flex gap-1.5 overflow-hidden">{item.tags.slice(0,3).map(tag=><span key={tag} className="shrink-0 rounded-full bg-white/10 px-2 py-1 text-[10px] font-bold">#{tag.replace(/^#/,"")}</span>)}</div>}
      <div className="mt-2 flex items-center gap-2 text-[10px] font-semibold text-white/50"><span>{count(Number(item.views||0))} views</span>{duration[item.id]>0&&<><span>•</span><span>{time(duration[item.id])}</span></>}</div>
    </div><div className="absolute bottom-[max(22px,env(safe-area-inset-bottom))] right-2 z-30 flex flex-col items-center gap-3 sm:right-[calc(50%-300px)]">
      <Action icon={liked[item.id]?<Heart className="size-6 fill-current"/>:<Heart className="size-6"/>} label={count(likes[item.id]??0)} active={!!liked[item.id]} onClick={()=>void like(item.id)}/>
      <Action icon={<MessageCircle className="size-6"/>} label="Comments" onClick={()=>{location.href=`/watch/${item.id}#comments`}}/>
      <Action icon={saved[item.id]?<Bookmark className="size-6 fill-current"/>:<Bookmark className="size-6"/>} label="Save" active={!!saved[item.id]} onClick={()=>void save(item.id)}/>
      <Action icon={<Share2 className="size-6"/>} label="Share" onClick={()=>{setShareItem(item);setPanel("share")}}/>
      <Action icon={muted?<VolumeX className="size-6"/>:<Volume2 className="size-6"/>} label={muted?"Sound":"Mute"} onClick={()=>{setMuted(v=>!v);Object.values(refs.current).forEach(v=>{if(v)v.muted=!v.muted})}}/>
      <Action icon={<MoreVertical className="size-6"/>} label="More" onClick={()=>setPanel("more")}/>
    </div></>}
    {paused[item.id]&&!clear&&<button onClick={()=>play(item.id,true)} className="absolute left-1/2 top-1/2 z-40 grid size-16 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-black/50 backdrop-blur-xl" aria-label="Play Clip"><Play className="ml-1 size-8 fill-current"/></button>}
   </section>})}
  </div>
  {!clear&&items.length>1&&<div className="pointer-events-none absolute bottom-3 left-1/2 z-30 hidden -translate-x-1/2 items-center gap-1 rounded-full bg-black/25 px-3 py-1.5 text-[10px] font-bold text-white/55 backdrop-blur sm:flex"><ChevronDown className="size-4 animate-bounce"/>Swipe for next</div>}
  {panel!=="none"&&<div className="absolute inset-0 z-[100] bg-black/35" onClick={()=>setPanel("none")}><div className="absolute bottom-0 left-0 right-0 mx-auto max-w-xl rounded-t-3xl border border-white/10 bg-[#0c1019]/98 p-3 pb-[max(14px,env(safe-area-inset-bottom))] backdrop-blur-xl" onClick={e=>e.stopPropagation()}>
   {panel==="more"&&<MorePanel item={items.find(x=>x.id===activeId)??items[0]} muted={muted} dataSaver={dataSaver} clear={clear} setClear={setClear} onMute={()=>setMuted(v=>!v)} onSaver={v=>{setDataSaver(v);localStorage.setItem("hktube-data-saver",v?"enabled":"disabled")}} onSpeed={()=>setPanel("speed")} onHelp={()=>setPanel("help")} onTune={tune}/>}
   {panel==="speed"&&<SpeedPanel speed={speed} setSpeed={v=>{setSpeed(v);Object.values(refs.current).forEach(x=>{if(x)x.playbackRate=v});setPanel("none")}}/>}
   {panel==="help"&&<HelpPanel/>}
   {panel==="share"&&shareItem&&<SharePanel item={shareItem} onShare={()=>void share(shareItem)} onCopy={()=>void copy(shareItem)} onClose={()=>{setPanel("none");setShareItem(null)}}/>}
  </div></div>}
 </div>
}

function Action({icon,label,onClick,active=false}:{icon:ReactNode;label:string;onClick:()=>void;active?:boolean}){return <button onClick={onClick} className={`flex flex-col items-center gap-1 transition active:scale-90 ${active?"text-white":"text-white/90"}`} aria-label={label}><span className={`grid size-11 place-items-center rounded-full border border-white/10 bg-black/35 backdrop-blur-xl ${active?"bg-white/15":""}`}>{icon}</span><span className="max-w-16 truncate text-[10px] font-bold">{label}</span></button>}

function MorePanel({item,muted,dataSaver,clear,setClear,onMute,onSaver,onSpeed,onHelp,onTune}:{item:ClipItem;muted:boolean;dataSaver:boolean;clear:boolean;setClear:(v:boolean)=>void;onMute:()=>void;onSaver:(v:boolean)=>void;onSpeed:()=>void;onHelp:()=>void;onTune:(i:ClipItem,t:"not_interested"|"hide_creator"|"hide_topic")=>Promise<void>}){return <div className="space-y-1"><Panel icon={<Zap className="size-5"/>} label="Clear screen" detail={clear?"On":"Hide interface while watching"} onClick={()=>setClear(!clear)}/><Panel icon={muted?<VolumeX className="size-5"/>:<Volume2 className="size-5"/>} label={muted?"Sound off":"Sound on"} detail="Clips session audio" onClick={onMute}/><Panel icon={<Gauge className="size-5"/>} label="Playback speed" detail="0.5× to 2×" onClick={onSpeed}/><Panel icon={<RefreshCw className="size-5"/>} label="Data saver" detail={dataSaver?"On":"Off"} onClick={()=>onSaver(!dataSaver)}/><Panel icon={<Sparkles className="size-5"/>} label="Not interested" detail="Tune your feed" onClick={()=>void onTune(item,"not_interested")}/><Panel icon={<UserRound className="size-5"/>} label="Hide creator" detail="Reduce this creator" onClick={()=>void onTune(item,"hide_creator")}/><Panel icon={<Flag className="size-5"/>} label="Report" detail="Open report flow" onClick={()=>{location.href=`/watch/${item.id}#comments`}}/><Panel icon={<CircleHelp className="size-5"/>} label="Clips help" detail="Gestures and controls" onClick={onHelp}/></div>}

function SpeedPanel({speed,setSpeed}:{speed:number;setSpeed:(v:number)=>void}){return <div className="px-2 pb-2"><h3 className="px-2 py-2 text-lg font-black">Playback speed</h3><div className="grid grid-cols-5 gap-2">{[0.5,0.75,1,1.5,2].map(v=><button key={v} onClick={()=>setSpeed(v)} className={`rounded-2xl border px-3 py-3 text-sm font-black ${speed===v?"border-white bg-white text-black":"border-white/10 bg-white/[.04]"}`}>{v}×</button>)}</div></div>}

function HelpPanel(){return <div className="space-y-3 px-2 pb-2"><h3 className="text-lg font-black">Clips controls</h3><p className="text-sm leading-6 text-white/70"><b className="text-white">Tap</b> pause/resume · <b className="text-white">double tap</b> like · <b className="text-white">press and hold</b> temporary 2× · <b className="text-white">swipe</b> next Clip.</p></div>}

function SharePanel({item,onShare,onCopy,onClose}:{item:ClipItem;onShare:()=>void;onCopy:()=>void;onClose:()=>void}){return <div className="space-y-3 px-2 pb-2"><div className="flex items-center justify-between"><h3 className="text-lg font-black">Share Clip</h3><button onClick={onClose} className="grid size-9 place-items-center rounded-full bg-white/10"><X className="size-4"/></button></div><p className="line-clamp-2 text-sm text-white/60">{item.title}</p><div className="grid grid-cols-2 gap-2"><button onClick={onShare} className="flex items-center justify-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-black text-black"><Share2 className="size-4"/>Share</button><button onClick={onCopy} className="flex items-center justify-center gap-2 rounded-2xl bg-white/[.06] px-4 py-3 text-sm font-black"><Link2 className="size-4"/>Copy link</button></div></div>}

function Panel({icon,label,detail,onClick}:{icon:ReactNode;label:string;detail:string;onClick:()=>void}){return <button onClick={onClick} className="flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left hover:bg-white/[.06]"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white/[.06]">{icon}</span><span className="min-w-0"><span className="block text-sm font-black">{label}</span><span className="block truncate text-xs text-white/50">{detail}</span></span><Check className="ml-auto size-4 text-white/25"/></button>}
