import { useEffect, useRef, useState, type ReactNode } from "react";
import { ArrowLeft, Bookmark, ChevronDown, Flag, Heart, MessageCircle, MoreVertical, Play, Share2, UserRound, Volume2, VolumeX } from "lucide-react";
import { Link } from "wouter";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { supabase } from "@/lib/supabase";
import { recordDiscoveryEvent, setRecommendationFeedback } from "@/lib/supabaseDiscovery";
import { recordVideoView, toggleChannelSubscription, toggleVideoLike, toggleVideoSave } from "@/lib/supabaseEngagement";
import { toast } from "sonner";

type ClipItem={id:string;title:string;description:string|null;video_path:string|null;thumbnail_path:string|null;views:number;likes_count:number;channel_id:string|null;tags:string[]|null};
type Channel={id:string;handle:string;name:string;avatar_url:string|null;subscriber_count:number};
type Panel="none"|"more"|"share"|"speed"|"help";

const media=(bucket:string,path:string|null)=>path?( /^https?:\/\//i.test(path)?path:supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl):null;
const compact=(n:number)=>n>=1_000_000?`${(n/1_000_000).toFixed(1)}M`:n>=1_000?`${(n/1_000).toFixed(n>=10_000?0:1)}K`:String(Math.max(0,Math.round(n)));
const clock=(n:number)=>{if(!Number.isFinite(n)||n<0)return "0:00";const s=Math.floor(n);return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`;};

export function ClipsView({items,mode,onModeChange}:{items:ClipItem[];mode:"for-you"|"following";onModeChange:(m:"for-you"|"following")=>void}){
 const {user}=useAuth();
 const [muted,setMuted]=useState(true),[autoplay,setAutoplay]=useState(true),[dataSaver,setDataSaver]=useState(false),[speed,setSpeed]=useState(1),[clearScreen,setClearScreen]=useState(false);
 const [paused,setPaused]=useState<Record<string,boolean>>({}),[liked,setLiked]=useState<Record<string,boolean>>({}),[saved,setSaved]=useState<Record<string,boolean>>({});
 const [likeCounts,setLikeCounts]=useState<Record<string,number>>(()=>Object.fromEntries(items.map(x=>[x.id,Number(x.likes_count||0)])));
 const [channels,setChannels]=useState<Record<string,Channel>>({}),[following,setFollowing]=useState<Record<string,boolean>>({});
 const [ready,setReady]=useState<Record<string,boolean>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[progress,setProgress]=useState<Record<string,number>>({}),[duration,setDuration]=useState<Record<string,number>>({}),[activeId,setActiveId]=useState(items[0]?.id??null);
 const [panel,setPanel]=useState<Panel>("none"),[shareTarget,setShareTarget]=useState<ClipItem|null>(null),[heart,setHeart]=useState<Record<string,boolean>>({});
 const refs=useRef<Record<string,HTMLVideoElement|null>>({}),seen=useRef(new Set<string>()),lastTap=useRef({id:"",at:0}),hold=useRef<number|null>(null),history=useRef<Record<string,number>>({}),buckets=useRef<Record<string,Set<string>>>({});

 useEffect(()=>{setAutoplay(localStorage.getItem("hktube-autoplay")!=="disabled");setDataSaver(localStorage.getItem("hktube-data-saver")==="enabled")},[]);
 useEffect(()=>{const ids=[...new Set(items.map(x=>x.channel_id).filter(Boolean))] as string[];if(!ids.length)return;let dead=false;void supabase.from("channels").select("id,handle,name,avatar_url,subscriber_count").in("id",ids).then(({data})=>{if(!dead)setChannels(Object.fromEntries((data??[]).map(x=>[String(x.id),x as Channel])))});return()=>{dead=true}},[items]);
 useEffect(()=>{if(!user)return;const ids=[...new Set(items.map(x=>x.channel_id).filter(Boolean))] as string[];if(!ids.length)return;let dead=false;void supabase.from("subscriptions").select("channel_id").eq("subscriber_id",user.id).in("channel_id",ids).then(({data})=>{if(!dead)setFollowing(Object.fromEntries((data??[]).map(x=>[String(x.channel_id),true])))});return()=>{dead=true}},[items,user?.id]);
 useEffect(()=>{setLikeCounts(Object.fromEntries(items.map(x=>[x.id,Number(x.likes_count||0)])));setPaused({});setReady({});setErrors({});setProgress({});setDuration({});setActiveId(items[0]?.id??null);refs.current={};seen.current.clear();history.current={};buckets.current={}},[items]);

 const play=(id:string)=>{const v=refs.current[id];if(!v)return;v.muted=muted;v.playbackRate=speed;void v.play().then(()=>setPaused(s=>({...s,[id]:false}))).catch(()=>setPaused(s=>({...s,[id]:true})))};
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{const id=(entry.target as HTMLElement).dataset.clipId;if(!id)return;const v=refs.current[id];if(!v)return;if(entry.isIntersecting&&entry.intersectionRatio>.68){setActiveId(id);if(autoplay)play(id);if(!seen.current.has(id)){seen.current.add(id);void recordVideoView(id).catch(()=>undefined);void recordDiscoveryEvent({eventType:"play_start",objectType:"short",objectId:id}).catch(()=>undefined)}}else v.pause()}),{threshold:[.2,.68,.9]});const timer=window.setTimeout(()=>document.querySelectorAll<HTMLElement>("[data-clip-id]").forEach(el=>observer.observe(el)),50);return()=>{window.clearTimeout(timer);observer.disconnect()}},[items,autoplay,muted,speed]);

 async function like(id:string,fromDoubleTap=false){if(!user)return startLogin();try{const r=await toggleVideoLike(id);setLiked(s=>({...s,[id]:r.liked}));setLikeCounts(s=>({...s,[id]:Number(r.count)}));if(fromDoubleTap&&r.liked){setHeart(s=>({...s,[id]:true}));window.setTimeout(()=>setHeart(s=>({...s,[id]:false})),700)}void recordDiscoveryEvent({eventType:r.liked?"like":"unlike",objectType:"short",objectId:id}).catch(()=>undefined)}catch(e){toast.error(e instanceof Error?e.message:"Unable to like Clip.")}}
 async function save(id:string){if(!user)return startLogin();try{const r=await toggleVideoSave(id);setSaved(s=>({...s,[id]:r}));void recordDiscoveryEvent({eventType:r?"save":"unsave",objectType:"short",objectId:id}).catch(()=>undefined);toast.success(r?"Saved to Library":"Removed from Library")}catch(e){toast.error(e instanceof Error?e.message:"Unable to save Clip.")}}
 async function follow(id:string){if(!user)return startLogin();try{const r=await toggleChannelSubscription(id);setFollowing(s=>({...s,[id]:r.subscribed}));setChannels(s=>({...s,[id]:s[id]?{...s[id],subscriber_count:Number(r.count)}:s[id]}));void recordDiscoveryEvent({eventType:r.subscribed?"follow":"unfollow",objectType:"channel",objectId:id}).catch(()=>undefined)}catch(e){toast.error(e instanceof Error?e.message:"Unable to update follow.")}}
 async function tune(item:ClipItem,type:"not_interested"|"hide_creator"|"hide_topic"){if(!user)return startLogin();try{const topic=type==="hide_topic"?(item.tags?.find(x=>x.toLowerCase()!=="shorts")??null):null;await setRecommendationFeedback(item.id,type,topic);setPanel("none");toast.success(type==="not_interested"?"Fewer Clips like this.":type==="hide_creator"?"Fewer Clips from this creator.":"Fewer Clips on this topic.")}catch(e){toast.error(e instanceof Error?e.message:"Unable to tune recommendations.")}}
 async function share(item:ClipItem){const url=`${window.location.origin}/watch/${item.id}`;try{if(navigator.share)await navigator.share({title:item.title,url});else{await navigator.clipboard.writeText(url);toast.success("Clip link copied")}void recordDiscoveryEvent({eventType:"share",objectType:"short",objectId:item.id}).catch(()=>undefined)}catch{}finally{setPanel("none");setShareTarget(null)}}
 async function copyLink(item:ClipItem){try{await navigator.clipboard.writeText(`${window.location.origin}/watch/${item.id}`);toast.success("Clip link copied");void recordDiscoveryEvent({eventType:"share",objectType:"short",objectId:item.id,context:{method:"copy_link"}}).catch(()=>undefined)}catch{toast.error("Could not copy the link.")}}

 function surface(id:string){const now=Date.now();if(lastTap.current.id===id&&now-lastTap.current.at<300){lastTap.current={id:"",at:0};void like(id,true);return}lastTap.current={id,at:now};window.setTimeout(()=>{if(lastTap.current.id===id&&Date.now()-lastTap.current.at>=290){const v=refs.current[id];if(!v)return;if(v.paused)play(id);else{v.pause();setPaused(s=>({...s,[id]:true}))}}},310)}
 function holdStart(id:string){if(hold.current)window.clearTimeout(hold.current);hold.current=window.setTimeout(()=>{const v=refs.current[id];if(v){v.playbackRate=2;toast("2× playback")}},380)}
 function holdEnd(id:string){if(hold.current)window.clearTimeout(hold.current);const v=refs.current[id];if(v)v.playbackRate=speed}

 if(!items.length)return null;
 return <div className="fixed inset-0 z-[80] overflow-hidden bg-black text-white">
  {!clearScreen&&<header className="pointer-events-none absolute inset-x-0 top-0 z-50 flex items-center justify-between px-3 pt-[max(12px,env(safe-area-inset-top))] sm:px-5"><Link href="/" className="pointer-events-auto grid size-10 place-items-center rounded-full bg-black/45 backdrop-blur-xl" aria-label="Close Clips"><ArrowLeft className="size-5"/></Link><div className="pointer-events-auto rounded-full bg-black/45 p-1 text-xs font-black backdrop-blur-xl"><button onClick={()=>onModeChange("for-you")} className={`rounded-full px-4 py-2 ${mode==="for-you"?"bg-white text-black":"text-white/70"}`}>For You</button><button onClick={()=>onModeChange("following")} className={`rounded-full px-4 py-2 ${mode==="following"?"bg-white text-black":"text-white/70"}`}>Following</button></div><button onClick={()=>setPanel("more")} className="pointer-events-auto grid size-10 place-items-center rounded-full bg-black/45 backdrop-blur-xl" aria-label="More"><MoreVertical className="size-5"/></button></header>}
  {clearScreen&&<button onClick={()=>setClearScreen(false)} className="absolute right-3 top-[max(12px,env(safe-area-inset-top))] z-[120] rounded-full bg-black/60 px-3 py-2 text-xs font-black backdrop-blur-xl">Show controls</button>}
  <div className="h-full snap-y snap-mandatory overflow-y-auto overscroll-y-contain [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
   {items.map((item,index)=>{const video=media("videos",item.video_path),thumb=media("thumbnails",item.thumbnail_path),channel=item.channel_id?channels[item.channel_id]:undefined,failed=errors[item.id],active=activeId===item.id;return <section key={item.id} data-clip-id={item.id} className="relative flex h-[100dvh] snap-start items-center justify-center overflow-hidden bg-black">
    {thumb&&<img src={thumb} alt="" aria-hidden="true" className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-500 ${ready[item.id]?"opacity-0":"opacity-100"}`}/>}
    {video&&<video ref={el=>{refs.current[item.id]=el}} src={video} playsInline autoPlay={autoplay&&index===0} muted defaultMuted loop preload={dataSaver?(index<1?"auto":"metadata"):(index<2?"auto":"metadata")} controls={false} disablePictureInPicture className="absolute inset-0 z-10 h-full w-full object-cover" onLoadedMetadata={e=>{const v=e.currentTarget;setDuration(s=>({...s,[item.id]:Number.isFinite(v.duration)?v.duration:0}));if(v.videoWidth>0&&v.videoHeight>0){setReady(s=>({...s,[item.id]:true}));setErrors(s=>{const n={...s};delete n[item.id];return n});v.muted=muted;v.playbackRate=speed;if(active&&autoplay)void v.play().catch(()=>undefined)}else setErrors(s=>({...s,[item.id]:"The video stream has no decodable video track."}))}} onCanPlay={e=>{const v=e.currentTarget;if(v.videoWidth>0&&v.videoHeight>0)setReady(s=>({...s,[item.id]:true}));if(active&&autoplay)void v.play().catch(()=>undefined)}} onTimeUpdate={e=>{const v=e.currentTarget,p=v.duration>0?v.currentTime/v.duration:0;setProgress(s=>({...s,[item.id]:p}));if(user&&Math.floor(v.currentTime)-(history.current[item.id]??0)>=5){history.current[item.id]=Math.floor(v.currentTime);void supabase.from("watch_history").upsert({user_id:user.id,video_id:item.id,progress_seconds:Math.floor(v.currentTime),watched_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"user_id,video_id"}).then(()=>undefined,()=>undefined)}const bucket=p>=.9?"watch_90_percent":p>=.75?"watch_75_percent":p>=.5?"watch_50_percent":p>=.25?"watch_25_percent":p>=.1?"watch_10_percent":null;if(bucket){const set=buckets.current[item.id]??new Set<string>();if(!set.has(bucket)){set.add(bucket);buckets.current[item.id]=set;void recordDiscoveryEvent({eventType:bucket,objectType:"short",objectId:item.id,watchSeconds:Math.floor(v.currentTime),positionSeconds:Math.floor(v.currentTime)}).catch(()=>undefined)}}}} onEnded={()=>void recordDiscoveryEvent({eventType:"complete",objectType:"short",objectId:item.id}).catch(()=>undefined)} onError={e=>{const code=e.currentTarget.error?.code;setErrors(s=>({...s,[item.id]:code?`Playback error ${code}.`:"Playback error."}));void recordDiscoveryEvent({eventType:"playback_error",objectType:"short",objectId:item.id,context:{media_error_code:code??null}}).catch(()=>undefined)}} onClick={()=>surface(item.id)} onPointerDown={()=>holdStart(item.id)} onPointerUp={()=>holdEnd(item.id)} onPointerCancel={()=>holdEnd(item.id)}/>}
    <div className="pointer-events-none absolute inset-0 z-20 bg-gradient-to-b from-black/30 via-transparent to-black/85"/>
    {active&&<div className="pointer-events-none absolute inset-x-0 top-0 z-30 h-1 bg-white/15"><div className="h-full bg-white" style={{width:`${Math.min(100,(progress[item.id]??0)*100)}%`}}/></div>}
    {failed&&<div className="absolute left-1/2 top-1/2 z-40 w-[min(88vw,430px)] -translate-x-1/2 -translate-y-1/2 rounded-3xl bg-black/90 p-5 text-center backdrop-blur-xl"><p className="font-black">This Clip cannot be played</p><p className="mt-2 text-xs text-white/60">{failed}</p><Link href={`/watch/${item.id}`} className="mt-4 inline-flex rounded-full bg-white px-4 py-2 text-xs font-black text-black"><Play className="mr-1 size-4 fill-current"/>Open video</Link></div>}
    {!ready[item.id]&&!failed&&video&&!clearScreen&&<div className="pointer-events-none absolute left-1/2 top-1/2 z-30 -translate-x-1/2 -translate-y-1/2 rounded-full bg-black/45 px-3 py-2 text-xs font-bold text-white/75 backdrop-blur-xl">Loading Clip…</div>}
    {heart[item.id]&&<div className="pointer-events-none absolute left-1/2 top-1/2 z-40 -translate-x-1/2 -translate-y-1/2 animate-ping"><Heart className="size-28 fill-current"/></div>}
    {!clearScreen&&<><div className="absolute bottom-[max(20px,env(safe-area-inset-bottom))] left-3 right-20 z-30 max-w-[650px] sm:left-1/2 sm:right-auto sm:w-[620px] sm:-translate-x-1/2 sm:pr-16"><div className="flex items-center gap-2"><Link href={channel?`/channel/${channel.handle}`:`/watch/${item.id}`} className="pointer-events-auto flex min-w-0 items-center gap-2"><span className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-full border border-white/30 bg-white/10">{channel?.avatar_url?<img src={channel.avatar_url} alt="" className="size-full object-cover"/>:<UserRound className="size-4"/>}</span><span className="truncate text-sm font-black">@{channel?.handle??"hktube"}</span></Link>{channel&&<button onClick={()=>void follow(channel.id)} className={`pointer-events-auto rounded-full px-3 py-1.5 text-[11px] font-black ${following[channel.id]?"bg-white/15":"bg-white text-black"}`}>{following[channel.id]?"Following":"Follow"}</button>}</div><h2 className="mt-2 line-clamp-2 text-base font-black leading-6 sm:text-lg">{item.title}</h2>{item.description&&<p className="mt-1 line-clamp-2 text-sm text-white/75">{item.description}</p>}<div className="mt-2 flex items-center gap-2 text-[10px] font-semibold text-white/50"><span>{compact(Number(item.views||0))} views</span>{duration[item.id]>0&&<><span>•</span><span>{clock(duration[item.id])}</span></>}</div></div>
    <div className="absolute bottom-[max(22px,env(safe-area-inset-bottom))] right-2 z-30 flex flex-col items-center gap-3 sm:right-[calc(50%-300px)]"><Action icon={liked[item.id]?<Heart className="size-6 fill-current"/>:<Heart className="size-6"/>} label={compact(likeCounts[item.id]??0)} onClick={()=>void like(item.id)} active={!!liked[item.id]}/><Action icon={<MessageCircle className="size-6"/>} label="Comments" onClick={()=>{window.location.href=`/watch/${item.id}#comments`}}/><Action icon={saved[item.id]?<Bookmark className="size-6 fill-current"/>:<Bookmark className="size-6"/>} label="Save" onClick={()=>void save(item.id)} active={!!saved[item.id]}/><Action icon={<Share2 className="size-6"/>} label="Share" onClick={()=>{setShareTarget(item);setPanel("share")}}/><Action icon={muted?<VolumeX className="size-6"/>:<Volume2 className="size-6"/>} label={muted?"Sound":"Mute"} onClick={()=>{setMuted(v=>!v);Object.values(refs.current).forEach(v=>{if(v)v.muted=!v.muted})}}/><Action icon={<MoreVertical className="size-6"/>} label="More" onClick={()=>setPanel("more")}/></div></>}
    {paused[item.id]&&!clearScreen&&<button onClick={()=>play(item.id)} className="absolute left-1/2 top-1/2 z-40 grid size-16 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-black/50 backdrop-blur-xl" aria-label="Play Clip"><Play className="ml-1 size-8 fill-current"/></button>}
   </section>})}
  </div>
  {!clearScreen&&items.length>1&&<div className="pointer-events-none absolute bottom-3 left-1/2 z-30 hidden -translate-x-1/2 items-center gap-1 text-[10px] font-bold text-white/55 sm:flex"><ChevronDown className="size-4 animate-bounce"/>Swipe for next</div>}
  {panel!=="none"&&<div className="absolute inset-0 z-[100] bg-black/40" onClick={()=>setPanel("none")}><div className="absolute bottom-0 left-0 right-0 mx-auto max-w-xl rounded-t-3xl bg-[#0c1019]/98 p-3 pb-[max(14px,env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}>
   {panel==="more"&&<MorePanel item={items.find(x=>x.id===activeId)??items[0]} muted={muted} dataSaver={dataSaver} clear={clearScreen} setClear={setClearScreen} onMute={()=>setMuted(v=>!v)} onSaver={v=>{setDataSaver(v);localStorage.setItem("hktube-data-saver",v?"enabled":"disabled")}} onSpeed={()=>setPanel("speed")} onHelp={()=>setPanel("help")} onTune={tune}/>}
   {panel==="speed"&&<div className="px-2 pb-2"><h3 className="py-2 text-lg font-black">Playback speed</h3><div className="grid grid-cols-5 gap-2">{[0.5,0.75,1,1.5,2].map(v=><button key={v} onClick={()=>{setSpeed(v);Object.values(refs.current).forEach(x=>{if(x)x.playbackRate=v});setPanel("none")}} className={`rounded-2xl border px-3 py-3 text-sm font-black ${speed===v?"border-white bg-white text-black":"border-white/10 bg-white/[.04]"}`}>{v}×</button>)}</div></div>}
   {panel==="help"&&<div className="space-y-2 px-2 pb-2"><h3 className="text-lg font-black">Clips controls</h3><p className="text-sm leading-6 text-white/70"><b className="text-white">Tap</b> pause/resume. <b className="text-white">Double tap</b> like. <b className="text-white">Press and hold</b> temporary 2×. <b className="text-white">Swipe</b> next Clip.</p></div>}
   {panel==="share"&&shareTarget&&<div className="space-y-3 px-2 pb-2"><h3 className="text-lg font-black">Share Clip</h3><p className="line-clamp-2 text-sm text-white/60">{shareTarget.title}</p><div className="grid grid-cols-2 gap-2"><button onClick={()=>void share(shareTarget)} className="rounded-2xl bg-white px-4 py-3 text-sm font-black text-black">Share</button><button onClick={()=>void copyLink(shareTarget)} className="rounded-2xl bg-white/[.06] px-4 py-3 text-sm font-black">Copy link</button></div></div>}
  </div></div>}
 </div>
}

function Action({icon,label,onClick,active=false}:{icon:ReactNode;label:string;onClick:()=>void;active?:boolean}){return <button type="button" onClick={onClick} className={`flex flex-col items-center gap-1 transition active:scale-90 ${active?"text-white":"text-white/90"}`} aria-label={label}><span className={`grid size-11 place-items-center rounded-full bg-black/35 backdrop-blur-xl ${active?"bg-white/15":""}`}>{icon}</span><span className="max-w-16 truncate text-[10px] font-bold">{label}</span></button>}

function MorePanel({item,muted,dataSaver,clear,setClear,onMute,onSaver,onSpeed,onHelp,onTune}:{item:ClipItem;muted:boolean;dataSaver:boolean;clear:boolean;setClear:(v:boolean)=>void;onMute:()=>void;onSaver:(v:boolean)=>void;onSpeed:()=>void;onHelp:()=>void;onTune:(i:ClipItem,t:"not_interested"|"hide_creator"|"hide_topic")=>Promise<void>}){return <div className="space-y-1"><Panel label={clear?"Restore screen":"Clear screen"} onClick={()=>setClear(!clear)}/><Panel label={muted?"Sound off":"Sound on"} onClick={onMute}/><Panel label="Playback speed" onClick={onSpeed}/><Panel label={dataSaver?"Data saver on":"Data saver off"} onClick={()=>onSaver(!dataSaver)}/><Panel label="Not interested" onClick={()=>void onTune(item,"not_interested")}/><Panel label="Hide creator" onClick={()=>void onTune(item,"hide_creator")}/><Panel label="Report" onClick={()=>{window.location.href=`/watch/${item.id}#comments`}}/><Panel label="Clips help" onClick={onHelp}/></div>}

function Panel({label,onClick}:{label:string;onClick:()=>void}){return <button type="button" onClick={onClick} className="flex w-full items-center rounded-2xl px-3 py-3 text-left text-sm font-black hover:bg-white/[.06]">{label}</button>}
