import { VideoCard } from "@/components/VideoCard";
import { VideoRecord } from "@/lib/video";
import { Button } from "@/components/ui/button";
import { BarChart3, Bell, Clapperboard, CircleDollarSign, FileText, FolderOpen, Layers3, MessageSquare, Plus, Settings2, Sparkles, Upload, UsersRound, Video } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

type Analytics = { totalViews: number; contentCount: number; regularCount: number; shortsCount: number };
type StudioTab = "Videos" | "Shorts" | "Posts" | "Writes" | "Drafts" | "Scheduled" | "Private" | "Unlisted";
const tabs: StudioTab[] = ["Videos", "Shorts", "Posts", "Writes", "Drafts", "Scheduled", "Private", "Unlisted"];

export function CreatorStudioHub({ videos, analytics }: { videos: VideoRecord[]; analytics: Analytics }) {
  const [tab, setTab] = useState<StudioTab>("Videos");
  const visible = tab === "Videos" ? videos.filter(v => v.category !== "shorts") : tab === "Shorts" ? videos.filter(v => v.category === "shorts") : [];
  const hasRealRecords = visible.length > 0;
  return <div className="mx-auto w-full max-w-[1480px] px-4 py-6 sm:px-7 lg:px-10">
    <header className="relative overflow-hidden rounded-[28px] border border-violet-300/15 bg-[#121529] p-6 shadow-2xl shadow-violet-950/20 sm:p-8">
      <div className="pointer-events-none absolute -right-20 -top-32 size-80 rounded-full bg-violet-500/20 blur-3xl" />
      <div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.24em] text-cyan-300">HKTube / Creator workspace</p><h1 className="mt-3 text-3xl font-black tracking-tight text-white sm:text-5xl">Creator Studio</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Your control center for published content, audience growth and creator workflows. All figures below come from your real HKTube account.</p></div><div className="flex flex-wrap gap-2"><Link href="/upload" className="inline-flex items-center rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-violet-400"><Upload className="mr-2 size-4" />Upload</Link><Link href="/settings" className="inline-flex items-center rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-semibold text-slate-200 hover:bg-white/10"><Settings2 className="mr-2 size-4" />Settings</Link></div></div>
      <div className="relative mt-8 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric icon={BarChart3} label="Total views" value={analytics.totalViews.toLocaleString()} /><Metric icon={Clapperboard} label="Published content" value={analytics.contentCount.toLocaleString()} /><Metric icon={UsersRound} label="Followers" value="—" muted /><Metric icon={CircleDollarSign} label="Revenue" value="—" muted /></div>
    </header>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><QuickAction icon={Video} label="Upload long video" href="/upload" /><QuickAction icon={Sparkles} label="Create a Short" href="/upload" /><QuickAction icon={FileText} label="Write a post" href="/posts" /><QuickAction icon={Layers3} label="Open analytics" href="#analytics" /></div>
    <section className="mt-7 overflow-hidden rounded-2xl border border-white/10 bg-[#101321]"><div className="border-b border-white/10 px-5 pt-5 sm:px-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-violet-300">Content center</p><h2 className="mt-1 text-xl font-bold text-white">Manage your content</h2><p className="mt-1 text-sm text-slate-400">Edit, analyze, schedule and control visibility from one place.</p></div><Link href="/upload" className="inline-flex items-center gap-2 text-sm font-semibold text-cyan-300 hover:text-cyan-200"><Plus className="size-4" />Create</Link></div><div className="mt-5 flex gap-1 overflow-x-auto pb-px" role="tablist">{tabs.map(item => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`shrink-0 border-b-2 px-3 py-3 text-sm font-semibold transition ${tab === item ? "border-violet-400 text-white" : "border-transparent text-slate-500 hover:text-slate-200"}`}>{item}</button>)}</div></div><div className="p-5 sm:p-6">{hasRealRecords ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map(video => <VideoCard key={video.id} video={video} />)}</div> : <EmptyTab tab={tab} />}</div></section>
    <section id="analytics" className="mt-5 grid gap-4 md:grid-cols-3"><InfoCard icon={BarChart3} title="Audience growth" text="Follower and watch-time reporting will appear when HKTube records those account events." /><InfoCard icon={MessageSquare} title="Recent comments" text="Comments linked to your published content will appear here." /><InfoCard icon={Bell} title="Alerts" text="Copyright, policy and monetization alerts will appear only when real checks return a result." /></section>
  </div>;
}
function Metric({ icon: Icon, label, value, muted }: { icon: typeof BarChart3; label: string; value: string; muted?: boolean }) { return <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><Icon className="size-4 text-cyan-300" /><p className={`mt-3 text-2xl font-black ${muted ? "text-slate-500" : "text-white"}`}>{value}</p><p className="mt-1 text-xs font-medium text-slate-400">{label}</p></div>; }
function QuickAction({ icon: Icon, label, href }: { icon: typeof Video; label: string; href: string }) { return <Link href={href} className="group flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-4 transition hover:-translate-y-0.5 hover:border-violet-300/30 hover:bg-violet-400/[.07]"><span className="grid size-10 place-items-center rounded-xl bg-violet-500/15 text-violet-200"><Icon className="size-5" /></span><span className="text-sm font-semibold text-slate-200 group-hover:text-white">{label}</span></Link>; }
function EmptyTab({ tab }: { tab: StudioTab }) { return <div className="grid min-h-44 place-items-center rounded-xl border border-dashed border-white/10 bg-white/[.02] p-6 text-center"><FolderOpen className="size-7 text-slate-600" /><h3 className="mt-3 font-bold text-white">No {tab.toLowerCase()} yet</h3><p className="mt-1 max-w-md text-sm leading-6 text-slate-500">HKTube will show real {tab.toLowerCase()} records here when you create or publish them.</p>{tab === "Writes" && <Link href="/posts" className="mt-4 inline-flex items-center rounded-lg bg-violet-500 px-3 py-2 text-xs font-bold text-white">Start writing</Link>}</div>; }
function InfoCard({ icon: Icon, title, text }: { icon: typeof BarChart3; title: string; text: string }) { return <article className="rounded-2xl border border-white/10 bg-[#101321] p-5"><Icon className="size-5 text-cyan-300" /><h3 className="mt-4 font-bold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article>; }
