import { Button } from "@/components/ui/button";
import { VideoCard } from "@/components/VideoCard";
import { VideoRecord } from "@/lib/video";
import { Bookmark, Clock3, FolderHeart, Library, ListVideo, WalletCards, UsersRound } from "lucide-react";
import { Link } from "wouter";

type SavedItem = { video: VideoRecord };
type HistoryItem = { video: VideoRecord };
type PlaylistItem = { id: number; title: string; visibility: string };
type FollowingItem = { channel: { id: number; displayName: string; handle: string; subscriberCount: number } };

export function LibraryHub({ saved, history, playlists, following }: { saved: SavedItem[]; history: HistoryItem[]; playlists: PlaylistItem[]; following: FollowingItem[] }) {
  const recent = saved.slice(0, 4).map(item => item.video);
  return <div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 lg:px-10">
    <section className="rounded-[28px] border border-violet-300/15 bg-[radial-gradient(circle_at_90%_0%,rgba(45,212,191,.12),transparent_26%),linear-gradient(135deg,rgba(124,92,255,.16),rgba(17,22,37,.92)_52%,rgba(17,22,37,.98))] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-200">Personal hub</p><div className="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-black tracking-tight text-white sm:text-4xl">Your Library</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">A private view of the real HkTube content you have saved, watched, collected, and followed.</p></div><Link href="/upload" className="inline-flex items-center rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-violet-400"><Library className="mr-2 size-4" />Your Videos</Link></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric icon={Bookmark} label="Saved" value={saved.length} /><Metric icon={Clock3} label="History" value={history.length} /><Metric icon={ListVideo} label="Playlists" value={playlists.length} /><Metric icon={UsersRound} label="Following" value={following.length} /></div></section>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><HubLink href="/library" icon={Bookmark} title="Watch Later" copy={`${saved.length} saved videos`} /><HubLink href="/history" icon={Clock3} title="History" copy={`${history.length} watched records`} /><HubLink href="/playlists" icon={ListVideo} title="Playlists" copy={`${playlists.length} collections`} /><HubLink href="/subscriptions" icon={UsersRound} title="Following" copy={`${following.length} channels`} /></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-[1fr_.72fr]"><div className="rounded-2xl border border-white/10 bg-[#111522] p-5"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-200">Saved for later</p><h2 className="mt-1 text-xl font-bold text-white">Recent saved videos</h2></div><Link href="/library" className="text-sm font-semibold text-cyan-200 hover:text-cyan-100">View all</Link></div>{recent.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2">{recent.map(video => <VideoCard key={video.id} video={video} />)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-white/12 bg-black/10 p-7 text-center"><Bookmark className="mx-auto size-6 text-violet-200" /><h3 className="mt-3 font-bold text-white">No saved videos yet</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-400">Save a real video from its watch page or a Short to keep it in your library.</p></div>}</div><aside className="space-y-4"><div className="rounded-2xl border border-cyan-300/15 bg-cyan-300/[.035] p-5"><div className="flex gap-3"><WalletCards className="mt-0.5 size-5 shrink-0 text-cyan-200" /><div><h2 className="font-bold text-white">Earnings and wallet</h2><p className="mt-1 text-sm leading-6 text-slate-400">Wallet records are available only when a configured payments or creator-revenue provider supplies them. No estimated balance is shown here.</p><Link href="/wallet" className="mt-3 inline-flex text-sm font-semibold text-cyan-200 hover:text-cyan-100">Open wallet</Link></div></div></div><div className="rounded-2xl border border-white/10 bg-[#111522] p-5"><div className="flex items-center gap-3"><FolderHeart className="size-5 text-violet-200" /><div><h2 className="font-bold text-white">Collections</h2><p className="mt-1 text-sm text-slate-400">Private playlists from your account.</p></div></div>{playlists.length ? <div className="mt-4 space-y-2">{playlists.slice(0, 3).map(playlist => <Link key={playlist.id} href="/playlists" className="flex items-center justify-between rounded-xl bg-white/[.035] px-3 py-2.5 text-sm text-slate-200 hover:bg-white/[.06]"><span className="truncate font-medium">{playlist.title}</span><span className="ml-3 text-xs text-slate-500">{playlist.visibility}</span></Link>)}</div> : <p className="mt-4 text-sm leading-6 text-slate-400">Create a playlist from the Playlists page when you are ready to organize saved videos.</p>}</div></aside></section>
  </div>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Bookmark; label: string; value: number }) { return <div className="rounded-2xl border border-white/10 bg-black/15 p-3"><Icon className="size-4 text-cyan-200" /><p className="mt-3 text-xl font-black text-white">{value}</p><p className="mt-1 text-xs font-medium text-slate-400">{label}</p></div>; }
function HubLink({ href, icon: Icon, title, copy }: { href: string; icon: typeof Bookmark; title: string; copy: string }) { return <Link href={href} className="rounded-2xl border border-white/10 bg-[#111522] p-4 transition hover:border-violet-300/25 hover:bg-white/[.04]"><Icon className="size-5 text-violet-200" /><h2 className="mt-4 font-bold text-white">{title}</h2><p className="mt-1 text-sm text-slate-400">{copy}</p></Link>; }
